### PR TITLE
Dev Branch

### LINKED ISSUE #857: [FEATURE PROPOSAL] Quit currently highlighted app
Hi, first of all - I totally enjoy Pop OS! Thanks for your wonderful product!

I have one feature proposal: the ability to quit the currently highlighted running app:

image

I feel it would be very interesting if I could be able to press `ctrl+Q` to quit the currently highlighted app. 

Any thoughts?

Thanks once again!

### LINKED ISSUE #919: Active hint for  tilix in quake mode extends to second monitor
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
tilix:
  Installed: 1.9.3-4build4
  Candidate: 1.9.3-4build4
  Version table:
 *** 1.9.3-4build4 500
        500 http://archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Active hint (yellow border) extends beyond primary monitor for Tilix in Quake mode.

**Steps to reproduce (if you know):**

1. Enable active hints (yellow borders)
2. Install Tilix
3. Start tilix in quake mode (usual F12 binding, `tilix --quake` command)
4. Observe undesired behaviour, see first screen bellow. 

**Expected behavior:**

Window does not extend beyond primary monitor, see second screen bellow (normal tilix maximised).

**Other Notes:**

Chosen background on which border between different monitors is clearly visible. 

image

image

### LINKED ISSUE #936: Window maximization isn't preserved when you launch a fullscreen video
**(1) Issue/Bug Description:**
In tiling mode, maximized windows are shrunk when you launch a fullscreen videos.

**(2) Steps to reproduce (if you know):**

1. While window tiling mode is on, open Firefox and go to https://blog.system76.com/post/648371526931038208/cosmic-to-arrive-in-june-release-of-popos-2104
2. Click the button to make the video fullscreen.
3. Close out of the fullscreen video.
4. The Firefox window that was maximized is restored/un-maximized and tiled with the other windows now.

**(3) Expected behavior:**
I expect the Firefox window to remain maximized when I leave the fullscreen video.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```pop-shell:
  Installed: 1.1.0~1617950178~20.10~163d207
  Candidate: 1.1.0~1617950178~20.10~163d207
  Version table:
 *** 1.1.0~1617950178~20.10~163d207 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status```

### LINKED ISSUE #940: Launcher conflicting with mouse position .
**(1) Issue/Bug Description:**

When the launcher is opened , if the mouse cursor is overlapping in any of the open windows lists , that window will be selected . 
I think the way to solve this is to give mouse and the keyboard its own individual selection. Or at least not to make a selection until the mouse pointer position is changed .
**(2) Steps to reproduce (if you know):*
1) open a few windows . 
put the mouse pointer where the launcher may appear
2) open the launcher with super +/ 
3) When the launcher is open , if the mouse pointer is in the position where a window list is shown, it will make a selection , which will conflict with the keyboard expected selection

**(3) Expected behavior:**
The expected behavior is for the first window to be selected initially . 

**(4) Distribution (run `cat /etc/os-release`):**
 

**(5) Gnome Shell version:**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

### LINKED ISSUE #942: VLC Exits full-screen when mouse is moved in tiling mode
**(1) Issue/Bug Description:**
VLC 3.0.12 exits full screen in tiling mode when mouse is moved. When tiling is turned off, then vlc does not exist full screen on mouse movement.

**(2) Steps to reproduce (if you know):**
1) Turn tiling on
2) Open a video in vlc
3) Press f to go fullscreen
4) Move mouse. The video will move to one half of the screen while playback controls show as if video is full-screen
5) Turn tiling off
6) Full screen the video
7) Now move the mouse and it will stay in full screen (expected behaviour)

**(3) Expected behavior:**
When mouse is moved when video is full screen in tile mode in vlc, the playback controls should appear while the video remains full screen. It should not move to one half of the screen.

**(4) Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```pop-shell:
  Installed: 1.1.0~1617950178~20.04~163d207
  Candidate: 1.1.0~1617950178~20.04~163d207
  Version table:
 *** 1.1.0~1617950178~20.04~163d207 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
It came with pop os

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 1080p laptop screen

**(9) Other Installed/Enabled Extensions:**
Draw on my screen for gnome

**(10) Other Notes:**
The tiling with VLC was working fine. Last couple of days it broke either due to some update I believe or a crash. Also, the problem started appearing after popos froze and had to be hard rebooted 3 times. These 3 crashes happened when vagrant virtualbox was running while vlc was playing a video and handbrake was encoding videos. I have used this configuration before and it was working fine.

### LINKED ISSUE #945: Launcher in incorrect position the first time it's opened
**(1) Issue/Bug Description:** The first time the launcher is opened after logging in or restarting GNOME Shell, it's shown lower on the screen and horizontally off-center. All subsequent times it's opened, it appears in a different position (higher and horizontally centered.)

**(2) Steps to reproduce (if you know):** Log into a session, open the launcher, then close it and open it again.

**(3) Expected behavior:** The launcher should launch in the same position every time.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10 and 21.04 beta.

**(5) Gnome Shell version:** 3.38.

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** `163d207`.

**(7) Where was Pop Shell installed from:** Pop!_OS PPA.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** Single 1080p display.

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only.

**(10) Other Notes:**
Position on first launch:
Screenshot from 2021-04-19 15-02-15
Position on subsequent launches:
Screenshot from 2021-04-19 15-02-20

### LINKED ISSUE #954: Cannot exclude Gtk4 windows from tiling
**(1) Issue/Bug Description:**

I can't get apps built against gtk4 excluded from tiling, there are a number of apps I use as widgets floating above my tiled windows.

**(2) Steps to reproduce (if you know):**

- Install the shortwave flatpak from <https://flathub.org/apps/details/de.haeckerfelix.Shortwave>
- Try to add it to your excluded windows
- when it fails press ctrl+shift+i and go to the global tab to verify it's running Gtk4.

**(3) Expected behavior:**

it floats over my windows.

**(4) Distribution (run `cat /etc/os-release`):**
 
Pop Os 20.04

**(5) Gnome Shell version:**

3.36

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1619032486~20.04~969e2c5
  Candidate: 1.1.0~1619032486~20.04~969e2c5
  Version table:
 *** 1.1.0~1619032486~20.04~969e2c5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Debian pkg? it's your os mate.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p notebook display, but it doesn't work on my multihead desktop either.

**(9) Other Installed/Enabled Extensions:**

- just perfect
- dash to dock
- hide top bar
- and I disabled desktop icons because they're ugly

**(10) Other Notes:**

The app doesn't use the pop theme either but that's an entirely different issue.

### LINKED ISSUE #956: Bug when tiling windows over excepted application
**(1) Issue/Bug Description:**
I have been seeing a lot of issues where tiling stops working well when there is an excepted window involved. I played around with this until I was able to find a way to reproduce the bug. I have also had issues where windows that are tiled overtop of an excepted window only take up a small part of the screen, and it might be related to this.

**(2) Steps to reproduce (if you know):**
fullscreen_tiling
This describes what happens when you have 2 monitors, but you get a similar behavior with 1 monitor:
1. Add a program to 'Floating Window Exceptions'. I added Gimp.
2. Open that program. It doesn't matter if it's maximized or not.
3. Open a Firefox window (or anything else that's tilable). Use Super + Right Arrow to move it to the 2nd screen.
4. Open a second Firefox window, and use the keyboard shortcut to move it all the way to the right of the first window.
5. With that window selected, hit Super + Left Arrow twice. That window stays on the left side of the second monitor, but the first window stretches out to fill the whole monitor.

**(3) Expected behavior:**
I would expect that the windows would tile on top of the excepted window, and fill the 1st monitor.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```pop-shell:
  Installed: 1.1.0~1619032486~20.10~969e2c5
  Candidate: 1.1.0~1619032486~20.10~969e2c5
  Version table:
 *** 1.1.0~1619032486~20.10~969e2c5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status```

### PR DESCRIPTION
**Pull request by mmstick**
Closes #954 
Closes #945 
Closes #940 
Closes #942 
Closes #936
Closes #919
Closes #857

### CODE REVIEW

**Comment by jacobgkau** [comment]
Regarding https://github.com/pop-os/shell/issues/857, it looks like `Super-Q` doesn't do anything in the launcher. Is there a reason `Ctrl-Q` is being used instead of `Super-Q`? It seems like the inconsistency would make this feature more difficult to discover.

Also, after quitting an app through the launcher with `Ctrl-Q`, I'm sometimes ending up with the closed app's overlay still on the screen:

Screenshot from 2021-04-29 09-59-40

This seems to happen when the window I'm quitting was not the focused window. The overlay prevents clicking on anything it's covering, and it remains until I un-focus that window.

**Comment by mmstick** [comment]
I can look into adding Super + Q. Ctrl + Q is added because all the launcher shortcuts are Ctrl-based

**Comment by mmstick** [comment]
Well, Super + Q won't work apparently

**Comment by jacobgkau** [comment]
I didn't consider that the rest of the launcher shortcuts use Ctrl. While a user might not consider that either, I don't think it's too big of an issue with that in mind.

**Comment by bflanagin** [comment]
#954 fixed: based on example
#940 fixed
#942 fixed: might need more testing
#945 seems fixed: @jacobgkau might have a better eye for it.
#936 still seems to be an issue with this PR. 

Can't test the multiple monitor issues.

**Comment by jacobgkau** [comment]
I'm seeing the active hint lag slightly when moving focus between displays:

https://user-images.githubusercontent.com/7199422/116614502-3e448b00-a8f7-11eb-8582-dbf2dbcf9300.mp4

When moving from the larger display to the smaller one, it takes its new size but remains on the old display for a moment; when going in the other direction, it moves to the new display but has the wrong size for a moment.

**Comment by jacobgkau** [comment]
The active hint lag is fixed. Regression testing passed on Groovy: [shell-pr958-groovy.txt](https://github.com/pop-os/shell/files/6443445/shell-pr958-groovy.txt)

- https://github.com/pop-os/shell/issues/956 is still occurring on this branch, so it needs to be re-opened if it's not being fixed here.
- I also noticed that if I start with no windows open on a multi-display setup, then open a floated (excepted) window followed by a tiling window, I'm unable to move the tiling window between displays using window management mode. Confirmed this is not a regression.

Things that are working as expected:
- https://github.com/pop-os/shell/issues/954 is fixed (a window-specific exception can't work without the wmclass, but an app-wide exception now works where it previously didn't.)
- https://github.com/pop-os/shell/issues/945 is fixed.
- https://github.com/pop-os/shell/issues/940 is fixed.
- https://github.com/pop-os/shell/issues/942 is fixed.
- https://github.com/pop-os/shell/issues/936 is fixed.
- https://github.com/pop-os/shell/issues/919 is fixed.
- https://github.com/pop-os/shell/issues/857 is implemented.

@mmstick Will this PR address https://github.com/pop-os/shell/issues/956, or should that be re-opened? If we're waiting on that, I can regression test on Focal so the rest of this can move forward.

**Comment by mmstick** [comment]
Will postpone the fix for 956

**Pull request merged**
