### PR TITLE
fix: Ability to create upper workspace when tiling is disabled

### LINKED ISSUE #586: Cannot create upper workspace with shortcut when tiling is disabled
**(1) Issue/Bug Description:**
Normally, If I press Super + Shift + Up in the first workspace I have, a new workspace is creating as my new first workspace and the window is moving to this workspace. 

With the latest updates, I'm just able to do this when window tiling is **enabled**, If I disable the tiling, I'm able to move my windows between workspaces with Super+Shift+ Up/Down, except creating a new one at the top.

**(2) Steps to reproduce (if you know):**
1. Disable the Tile Windows option from the extension.
2. Go to your first workspace.
3. Open at least 2 apps/windows.
4. Press Super+Shift+Up to create a new workspace at the top and move the window to that workspace.

**(3) Expected behavior:**
A new workspace should be created at the top and the window should move to that workspace. 

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```  Installed: 0.1.0~1601418772~20.04~b9f8d96
  Candidate: 0.1.0~1601418772~20.04~b9f8d96
  Version table:
 *** 0.1.0~1601418772~20.04~b9f8d96 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Pop!_Os is coming with Pop Shell :)

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Just one 14" laptop monitor which is 1080p.

**(9) Other Installed/Enabled Extensions:**

Caffeine, Clipboard Indicator, Dash to Dock, Disconnect Wifi, GSConnect, Remove Alt+Tab Delay v2, Sound Input&Output Device Chooser, Unite, User themes, and the rest are builtin extensions like system76 power etc.

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by mmstick**
Closes #586

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
On `0f01180`, starting with two windows and auto-tiling disabled, I am still not able to move one of the windows to a new upper workspace using `Super+Shift+Up`. I am only able to use that shortcut successfully after I turn auto-tiling on.

**Comment by mmstick** [comment]
I believe this one's working correctly now.

**Review by jacobgkau — APPROVED** [review]
It's a little jarring/inconsistent that there's no animation for moving to a new upper workspace while there is an animation for moving to any other workspace. That's not a regression, though, it's just more noticeable when tiling is off. Is an animation not possible because of how this action works? (I understand from [the comments](https://github.com/pop-os/shell/blob/e3d137e1b0aee120e74e078dd48343339a429933/src/extension.ts#L998) that we add a new workspace below and push all the non-selected windows down, which I would assume doesn't come with an animation?)

I checked upstream GNOME on Fedora 32, and they do have an animation when moving a window to a new top workspace (although the animation seems to go in the wrong direction-- the non-selected windows disappear, like they do in Pop, and the selected window slides _down_ into the new upper workspace. I think they're moving the window first and then animating the change to that workspace, although I'm not sure why the non-selected windows disappear in that case.) I think this fix can go to dev now and the animation can possibly be addressed later if it's reasonable.

**Comment by mmstick** [comment]
An animation could be added to give an illusion that it's moving upwards when it's really just other windows are moving down.

**Pull request merged**
