### PR TITLE
Shell Improvements

### LINKED ISSUE #1394: launcher is off-center if dock is on the right/left
image
image

this is pop os 21.10, but still happens in pop os 22.04

### LINKED ISSUE #1430: When moving window between two half-split workspaces, it moves to the wrong side
**(1) Issue/Bug Description:** When moving a window between two workspaces that each have two tiled apps (horizontally split), moving the app on the right side down a workspace will move the app to the left side.

**(2) Steps to reproduce (if you know):**
1. Arrange two workspaces with two apps each
2. Focus the second app on the first workspace
3. Move that app to the second workspace with Super+Shift+Down

**(3) Expected behavior:** The app should stay closer to where it was on the previous workspace (in this case, ideally top right since it's coming from above, but top or bottom on the right would be better than anywhere on the left.)

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04

**(5) Gnome Shell version:** 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** add07f1 (`master_jammy`) or 053d822 (`shell_jammy`).

**(7) Where was Pop Shell installed from:** Pop!_OS release and staging repositories.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only.

**(10) Other Notes:** Video:

https://user-images.githubusercontent.com/7199422/168129459-9933a5ee-2370-418b-a8eb-da2b80da24b2.mp4

This happens regardless of which window on the second workspace had focus before moving the third window onto the workspace.

### LINKED ISSUE #1440: Maximized floating window returns to previous state after losing & regaining focus
**(1) Issue/Bug Description:**

When maximizing a window included in the floating windows exception list, it will return to an un-maximized state after switching focus to another window, then switching back

**(2) Steps to reproduce (if you know):**

- Add a window to the floating windows list
- Maximize the window
- Focus another window
- Switch focus back to the original maximized window

**(3) Expected behavior:**

The window should remain maximized

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

GNOME 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652463555~22.04~034fb14
  Version table:
 *** 1.1.0~1652463555~22.04~034fb14 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:**

Included as part of PopOS install

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Two monitors, one is a built in laptop display (oryx pro), another is a 2560x1440 144Hz HDMI monitor above it

**(9) Other Installed/Enabled Extensions:**

Dash 2 Panel
Sound Input & Output Device Chooser
CPU Power Manager

**(10) Other Notes:**

### LINKED ISSUE #1441: Active hint sometimes missing after moving floated window between workspaces
**(1) Issue/Bug Description:** After moving a floating window between workspaces with the keyboard, for some sequences, the active hint doesn't show after the move (so no window has the active hint.)

**(2) Steps to reproduce (if you know):**
1. Tile two windows on a workspace
2. Focus one of the windows
3. Open the Workspaces menu and move the _other_ (non-focused) window to a new workspace
4. Move to that new workspace
5. Float the window with Super-Shift-G
6. Move the window back to the original workspace with the keyboard

**(3) Expected behavior:** The floated, focsued window should have an active hint.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04

**(5) Gnome Shell version:** 42

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** `mater_jammy` branch (034fb14), `shell_jammy` branch (8d6ebf6).

**(7) Where was Pop Shell installed from:** Pop!_OS staging & release repos

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only

**(10) Other Notes:** Video:

https://user-images.githubusercontent.com/7199422/169096219-ee740895-5fa6-465b-8ba7-9608068db7d6.mp4

Not caused by or fixed by https://github.com/pop-os/shell/pull/1439, but discovered while testing that PR.

### LINKED ISSUE #1443: Wrong window focus when switching workspaces and in stacking mode
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
I have two workspaces
First of them has stacking mode with for example 3 applications A B C, last application opened is app C
I try to open app B from second workspace then I'm moved to proper workspace but still app C is visible
Then to open app B I have to pick it from bottom panel or somewhere else again and then it's focused correctly

**Steps to reproduce (if you know):**
Described above

**Expected behavior:**
When switching windows it should be focused immediately on correct one

### LINKED ISSUE #1444: Mouse jumping when clicking on dock item that's open on a different workspace
I've noticed a strange bug on Pop_OS with the cosmic dock where clicking on an item in the dock, if the window is on a different workspace, will jump my mouse position to the top-left corner of the application that I selected. But not always?

Please let me know how I can give you further information about the version of the dock I'm running. I didn't see anything obvious in the settings

### LINKED ISSUE #1447: make local-install error
(1) Issue/Bug Description:

make local-install throws the following error:
src/extension.ts:1007:25 - error TS6133: '_entity' is declared but its value is never read.

1007             for (const [_entity, compare] of this.windows.iter()) {
                             ~~~~~~~


Found 1 error.

make: *** [Makefile:38: compile] Error 2


(2) Steps to reproduce (if you know):

Following the instructions for Using Pop Shell on other GNOME Desktops for Ubuntu-Based Distros

(3) Expected behavior:

Pop Shell's installed

(4) Distribution (run cat /etc/os-release):

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

(7) Where was Pop Shell installed from:

https://github.com/pop-os/shell

(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):

(9) Other Installed/Enabled Extensions:

(10) Other Notes:

### LINKED ISSUE #1448: Kodi fullscreen not working with window tiling on
**(1) Issue/Bug Description:
Putting Kodi into fullscreen mode with window tiling on is not working since latest update.  The system bar and dock are overlyaed.  This does not happen with other applications such as Firefox or VLC**

**(2) Steps to reproduce (if you know):
Put Pop-Shell in tilting mode, open Kodi in fullcreen**

**(3) Expected behavior:
The Kodi app should fill the entire screen**

**(4) Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os**
 

**(5) Gnome Shell version: 42.1**

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Installed: 1.1.0~1652994129~22.04~0358b15
  Candidate: 1.1.0~1652994129~22.04~0358b15
  Version table:
 *** 1.1.0~1652994129~22.04~0358b15 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**(7) Where was Pop Shell installed from:
Pop-OS installation**

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):*
1 HDMI connected TV 1920X1080, 60Hz*

**(9) Other Installed/Enabled Extensions:
none**

**(10) Other Notes:**

### LINKED ISSUE #1449: Launching launcher in game locks out whole system
**(1) Issue/Bug Description:**
Tested on Overwatch and League of Legends. Sometimes, when playing games and hit Super key for launcher, launcher doesn't become visible and orange highlight is also not visible. But at the same time it locks out computer keyboard, so that after pressing super key, I cannot longer do anything on my computer. Everything still works as I see game playing still, music also playing, but I cannot use my keyboard and mouse for anything. I can move my mouse but clicking is not registered by system. Alt-tab, super+d, spamming super key doesn't do anything. Only fix is to restart my computer.

**(2) Steps to reproduce (if you know):**

Like written above.

**(3) Expected behavior:**

Fully working launcher, not soft-locking whole computer

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

42.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1652994129~22.04~0358b15
  Candidate: 1.1.0~1652994129~22.04~0358b15
  Version table:
 *** 1.1.0~1652994129~22.04~0358b15 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
With Pop_Os installation

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Only laptop screen.

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by mmstick**
Closes #1394 
Closes #1444 
Closes #1443
Closes #1441
Closes #1440
Closes #1430

### Added May 26th

Closes #1447 
Closes #1448
Closes #1449

### CODE REVIEW

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
The following issues are all fixed:

- [x] [#1394](https://github.com/pop-os/shell/issues/1394)
- [x] [#1444](https://github.com/pop-os/shell/issues/1444)
- [x] [#1443](https://github.com/pop-os/shell/issues/1443)
- [x] [#1441](https://github.com/pop-os/shell/issues/1441)
- [x] [#1440](https://github.com/pop-os/shell/issues/1440)
- [x] [#1430](https://github.com/pop-os/shell/issues/1430)

There are some caveats. For issue [#1441](https://github.com/pop-os/shell/issues/1441). Following the steps to try to recreate the issue can cause `Super`+`O` to stop working. For issue [#1430](https://github.com/pop-os/shell/issues/1430) the window moves to the bottom not top right but does stay on the right. It was mentioned in the issue this behavior would be better than the previous of switching to the left side so it may be acceptable.

Zoom is now working correctly in the System Exceptions for Floating Window Exceptions.

Most regression testing passed. With the following exceptions.

[shell-testing.txt](https://github.com/pop-os/shell/files/8757039/shell-testing.txt)

   - If there is a stack on the a workspace and a window is moved from another workspace with the keyboard it is placed into the stack.

https://user-images.githubusercontent.com/11048214/169880053-29d3b194-4401-40b0-a43d-1807f6862258.mp4

   - On rare occasions when adding a window or application to Floating Window Exceptions the window to pick the type of exception (window or app) is placed behind the open windows on the current workspace. This also sometimes results in the cursor becoming stuck as an I-Beam  pointer.
   -  No LibreOffice apps or windows keep their Floating Window Exception after closing and reopening.
   -  When the last or first window in a stack is Nautilus and it is moved out of the stack it will sometimes cause a widow overlapping issue. This seems to happen more often on a 4k screen set to 200% scaling, but has also happend on 1080p set to 100%.


stack1
stack2

This may be related to an issue where Calculator, VLC, Nautilus, Calendar (these are apps I found to have the issue there may be others) overlap other windows when tiling several windows on a workspace. This was happening before, but the overlapping when moving out of a stack is new.  
   
Screenshot from 2022-05-23 10-15-05

**Comment by jacobgkau** [comment]
> For issue https://github.com/pop-os/shell/issues/1430 the window moves to the bottom not top right but does stay on the right. It was mentioned in the issue this behavior would be better than the previous of switching to the left side so it may be acceptable.

Indeed, this PR's behavior is an improvement. Top/bottom based on which direction workspace the window is coming from would be more complicated and while it would be nice, we don't need to hold this improvement waiting for that.

> If there is a stack on the a workspace and a window is moved from another workspace with the keyboard it is placed into the stack.

From what I'm seeing, that's only happening if the stack is on the left side (because the maximized window is going to the left side of the tree, which doesn't really seem wrong to me since that's where its top-left corner is). If I have the stack on the right, it doesn't go into there, so this description is not accurate.

https://user-images.githubusercontent.com/7199422/169882539-ff3f0116-d96c-4155-95bb-0dab8e53b8df.mp4

Can you confirm if I'm understanding this correctly or if you're seeing something different than that?

**Comment by n3m0-22** [comment]
No you are understanding correctly, and I can confirm I get the same result if the stack is on the right. The reason I mentioned it is because I do not see it happening prior to installing this PR.

**Comment by mmstick** [comment]
Do these issues also happen on the master version? No changes have been made to exceptions, and the only tiling change was window placement when a window is moved by keyboard.

**Comment by mmstick** [comment]
Yeah, things like window overlapping cannot be solved until we have our own DE.

**Comment by n3m0-22** [comment]
I've been double checking everything. I'm seeing #1440 happening again.

**Comment by n3m0-22** [comment]
Fixed:
#1394
#1430
#1440
#1441
#1443
#1444
#1445
#1448

**Comment by n3m0-22** [comment]
In regards to the issue listed above about windows moved by keyboard being added to a stack in the next workspace. I have tested this with and without this PR as well as with master and with and without this PR. It seems to be happening no matter what. I think it is being cause by something else and is not a regression.

**Comment by mmstick** [comment]
I'll create an issue to remind myself about it.

**Comment by n3m0-22** [comment]
Tested #1449 against several games both native and proton. I was able to recreate the issue and with this PR I am no longer seeing it.

**Review by n3m0-22 — APPROVED** [review]
All previous issues have been resolved.

**Review by jackpot51 — APPROVED** [review]

**Comment by MyNameIsArko** [comment]
Hi, is this changes already in the pop os repository, or we need to wait a little bit longer?

**Comment by jacobgkau** [comment]
@MyNameIsArko You can check if you have the update by comparing the [commit hash](https://github.com/pop-os/shell/commits/master_jammy) to the number at the end of the version in your `apt policy pop-shell` output. The currently-released version is 42102e9, which does include this PR's commits.

**Pull request merged**
