### PR TITLE
feat: Restore window dimensions on detach

### LINKED ISSUE #379: Tiling overwrites default application sizes
**Distribution:**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version**:
  Installed: 0.1.0~1589754807~20.04~e5f3b4d
  Candidate: 0.1.0~1589754807~20.04~e5f3b4d
  Version table:
     0.1.0~1589754807~20.04~e5f3b4d 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
After using the tiling mode and switching it off, the next time you launch an application, it opens with the size and in the position that is was, when tiling was enabled. Which can be annoying, because without the other applications being open it does not form a nice grid, and looks a bit funny.

**Steps to reproduce :**
1. Have an application sized the way you like it.
2. Turn on tiling.
3. Close the application.
4. Turn tiling off.
5. Reopen the application.
6. The application opens with its previous "tiling size' instead of the one you liked.

**Expected behavior:**
In my opinion the size and position of an application should be ignored, when tiling was enabled and applications should open with the size and position what they had the last time before tiling was enabled. It would make the experience much better.

**Other Notes:**
Tiling is awesome, I love pop-shell very much, thanks for making my life easier!

### PR DESCRIPTION
**Pull request by mmstick**
Closes #379

### CODE REVIEW

**Review by jacobgkau — COMMENTED** [review]
This doesn't seem to work entirely reliably.

- Nautilus still stays at its tiled position when resized/restarted after resizing: https://www.dropbox.com/s/3vu7ugtmweuuav2/shell-pr579-screencast1.webm?dl=0 
- If a window is quit while tiling is on, it opens in its tiled size when launched while tiling is off (this example uses Audacity) -- this sounded like what #379 was referring to: https://www.dropbox.com/s/8c770gkoenlhf5u/shell-pr579-screencast2.webm?dl=0 
- Windows seem to forget their previous dimensions if they're moved between workspaces while tiling is enabled: https://www.dropbox.com/s/b76u6bpxpmij9dq/shell-pr579-screencast3.webm?dl=0 

While testing with Firefox and Audacity, I've also had multiple cases where only one window would remember its position after enabling/disabling tiling (sometimes one, sometimes the other.) Examples:

- Audacity misbehaving: https://www.dropbox.com/s/kqeqe6hj9ylkaus/shell-pr579-screencast4.webm?dl=0 
- Firefox misbehaving: https://www.dropbox.com/s/dd29qat5txcm7u9/shell-pr579-screencast5.webm?dl=0 

If any of this is expected, I would need more detailed information about the expected behavior.

**Comment by mmstick** [comment]
I'm looking into it. This is helpful

**Comment by mmstick** [comment]
I was able to fix everything but tiles that are destroyed while being auto-tiled. By the time we get the destroy signal from a `Meta.Window`, the window has already been destroyed, and it's no longer possible to resize it so that GNOME remembers its original location.

**Comment by jacobgkau** [comment]
Understood re: destroyed while auto-tiled. May want to make a note about that in the issue so it doesn't get re-opened, since the test case described will still "fail."

Moving between workspaces still loses the saved size: https://www.dropbox.com/s/16w2ageovlutmof/shell-pr579-screencast6.webm?dl=0 Is this one something that can be worked around, or will it also not work?

**Comment by jacobgkau** [comment]
Positions are now correctly being remembered even when windows are moved between workspaces. However, I'm now seeing a ghost window issue: https://www.dropbox.com/s/qweccsfbp3zyx50/shell-pr579-screencast7.webm?dl=0 

This is on `ffac96f`, and is near the beginning of the testing.md procedure. After arranging the windows and then swapping two of the windows, I'm not able to resize certain windows (in this example, the stack won't resize, and neither will the terminal.) When I try to move one of the windows that won't resize, I get a ghost window. This is not happening in master.

Here's an example without a stack: https://www.dropbox.com/s/p5bmh7l9s50boel/shell-pr579-screencast8.webm?dl=0 It looks like the swap is what causes the issue, as I'm able to resize windows fine until I swap two windows (happens with both differently-sized and same-sized windows.)

**Comment by mmstick** [comment]
@jacobgkau I think I've fixed the problem. I'm able to swap and resize without issues now.

**Comment by jacobgkau** [comment]
Enabling and disabling tiling in quick succession breaks the pre-tiling memory: https://www.dropbox.com/s/fryjv5eeqyfdim5/shell-pr579-screencast9.webm?dl=0 Is this an expected performance limitation?

**Comment by mmstick** [comment]
I'll see if I can work around that scenario

**Comment by mmstick** [comment]
@jacobgkau That last commit will have the shell track when windows are moving, and delay toggling of tiling when they are moving.

**Comment by jacobgkau** [comment]
That fix did work to prevent the shell from forgetting sizes when quickly toggling on and back off. However, I'm now not able to turn tiling off after closing a window with `Super+Q`. (Neither the keyboard shortcut nor the on/off switch in the top-right menu work; clicking the on/off switch flips the switch, but doesn't turn off tiling. The keyboard shortcut does not flip the switch.)

**Comment by mmstick** [comment]
@jacobgkau Got that one fixed too

**Comment by jacobgkau** [comment]
Regression testing is passing again. I'm seeing some interesting behavior with remembered positions for stacked windows: https://www.dropbox.com/s/shvzxpzvvy56gzs/shell-pr579-screencast10.webm?dl=0 

It seems the window's not properly restored to its prior position if I disable tiling while it was stacked; however, if I re-enable and re-disable tiling, it goes back to its original position. This doesn't seem intentional.

**Comment by mmstick** [comment]
Toggling tiling wasn't triggering the `on_detach()` signals for stacked windows. Now working

**Comment by jacobgkau** [comment]
@mmstick On `d60646a`, stacked windows restore their positions, but non-stacked windows do not restore their positions.

**Comment by mmstick** [comment]
Fixed

**Comment by jacobgkau** [comment]
I am getting misplaced windows if I press the arrow key too quickly for the shell to keep up: https://www.dropbox.com/s/w9pv6d3ggqs0l3s/shell-pr579-screencast11.webm?dl=0 

In comparison, master (`50d953a`) simply swaps the windows if I try to move too fast, I don't end up with any empty spaces or overlapping windows: https://www.dropbox.com/s/ctpl3ks7x8t85hy/shell-pr579-screencast12.webm?dl=0

**Review by jackpot51 — APPROVED** [review]

**Comment by mmstick** [comment]
Took a while, but I've rearranged the way window movements are scheduled, to eliminate any risk of operations being applied out-of-order due to window animations, and ensuring a delay between movements of the same window to stop the animation quirks. This may fix the blurry windows too.

**Comment by jacobgkau** [comment]
That did fix the visual glitch. Certain actions (especially repetitive ones) are noticeably slow now. For example, with tiling disabled, enter window management mode with `Super+Enter` and try to move a window around-- if I press the arrow keys fast enough (or even hold them down), then the window continues moving after I let go of the key. I can even exit window management mode, then re-enter window management mode, and the window starts moving again without having to touch the arrow keys. I don't think it's okay for actions to queue up like this: https://www.dropbox.com/s/85m5n1kuumxduu4/shell-pr579-video1.webm?dl=0 

Notice how the second time I entered window management mode, I didn't press the right arrow key at all, that movement was entirely left over from the first move. Even if movements are slow, I would expect them to at least be cleared/dropped when window management mode is exited.

I can also feel a difference moving windows around while tiling is enabled (it seems to be slower even when animations are disabled), but the above example is the easiest to quantify.

**Comment by jacobgkau** [comment]
Thinking further, I realize that you made movements queue to solve a problem, and now I've called the queueing a problem. Maybe, while it makes sense to queue some actions (like moving a window in tiling mode), it doesn't make sense to queue others (like moving a window in non-tiling/floating mode), especially when the added delay hinders those features more than the queuing is helping them (moving in non-tiling/floating mode is basically instant on master.)

**Comment by mmstick** [comment]
Non-tiling/floating windows aren't affected by this. The queue is only for when a window is moved by the auto-tiler, and when a movement is requested by the user through the tiler. I could limit the number of movements that will be scheduled, and drop the queue when exiting management mode. I can also increase the animation speed since the delay is based solely around that.

**Comment by mmstick** [comment]
@jacobgkau See if these changes make the experience better

**Comment by jacobgkau** [comment]
> Non-tiling/floating windows aren't affected by this. The queue is only for when a window is moved by the auto-tiler, and when a movement is requested by the user through the tiler.

I may be misunderstanding you, but moving windows using window management mode with auto-tiling disabled was most certainly affected by this. The issue I showed in my video above is not reproduceable on master/stable, and is also not reproduceable after the last three commits. Would this be included in "movement being requested by the user through the tiler?" 

The movement is at a more acceptable level now, although it's still slower than before. Here are two examples of what happens when I hold down the right arrow key before and after this branch:

- Moving a window across the screen on current stable: https://www.dropbox.com/s/3qkfdrn2ktk11vg/shell-pr579-screencast14.webm?dl=0 
- Moving a window across the screen on this branch: https://www.dropbox.com/s/e05a651xtf8a010/shell-pr579-screencast15.webm?dl=0 

The difference in speed is clearly visible. While that movement being slower isn't a big problem, the visual glitch from before last night's changes has reappeared: https://www.dropbox.com/s/as6ysk8jis4vd5v/shell-pr579-screencast16.webm?dl=0

There are two different things happening here:
1. If I try to move the window too quickly, it moves back to its previous location. This also happens on master.
2. When this occurs, the other window turns invisible until it's focused again. This does not happen on master, that's the regression.

I hope this clarifies things, let me know if there are limitations/expectations I'm not taking into account.

**Comment by mmstick** [comment]
I can't seem to replicate a disappearing window, even with the same applications and layout.

**Comment by jacobgkau** [comment]
Hmm. After switching to a separate machine (the addw2 with a relatively fresh install), I was able to make it happen on my second try after adding this branch and restarting the shell (it didn't happen on stable.)

I saw some cases earlier where the window didn't disappear until I exited window management mode: https://www.dropbox.com/s/5ax9jzl76tun62q/shell-pr579-screencast18.webm?dl=0 

I tried to get logs, but even set to `DEBUG`, I'm just seeing a single `gnome-shell[1965]: Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).` every time I exit window management mode, no other logging. Is there any other info I could get to help?

**Comment by mmstick** [comment]
I'm going to try something out. A shot in the dark, but I have some suspicions about the cause.

**Comment by mmstick** [comment]
The overlay movements should be back to normal speed. Hopefully this change will fix the disappearing windows too

**Review by jacobgkau — APPROVED** [review]
The visual glitch with disappearing windows (and the window swapping when moving too quickly glitch) is gone, so that's great. Moving windows around in tiling mode feels much snappier now. Moving floated/non-tiled windows in management mode is back to the way it was before.

Ran through regression testing again, and everything's looking good now. [shell-pr579-run6.txt](https://github.com/pop-os/shell/files/5337089/shell-pr579-run6.txt)

**Pull request merged**
