### PR TITLE
Shell Fixes

### LINKED ISSUE #891: Ghost window after dragging windows out of stacks
**(1) Issue/Bug Description:** Some sequences of creating and removing stacks using the mouse can lead to a ghost window.

**(2) Steps to reproduce (if you know):**
- Create a stack in the bottom-left quadrant of a tree.
- Drag one of the windows out of the stack.
- Focus the remaining window and re-stack it with `Super+S`.
- Drag the remaining window (now in its own stack) over the first window to create a two-window stack.
- Drag one of the two windows out of that new stack.
- Drag the remaining window onto the first window again.

**(3) Expected behavior:** Ghost windows should never occur.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.10

**(5) Gnome Shell version:** 3.38.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
- `master` (`6b2287f`)
- `unstack` (`fe2bb4a`)

**(7) Where was Pop Shell installed from:** Staging repos.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p.

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults.

**(10) Other Notes:**
- Video example 1: https://www.dropbox.com/s/kpkgsav0ahwsr68/shell-pr888-screencast2.mkv?dl=0 
- Video example 2: https://www.dropbox.com/s/uh51bnvod5ea2a4/shell-pr888-screencast3.mkv?dl=0

### PR DESCRIPTION
**Pull request by mmstick**
Closes #891

### CODE REVIEW

**Comment by jacobgkau** [comment]
This does not currently fix https://github.com/pop-os/shell/issues/891, I'm still able to reproduce that ghost window using the same steps.

shell-pr897-gif1

**Comment by bflanagin** [comment]
Can confirm #776 is fixed in this PR. Will retest after next revision.

**Comment by jacobgkau** [comment]
Confirmed this now fixes https://github.com/pop-os/shell/issues/891 after the most recent change. I can no longer recreate that ghost window.

This does not seem to fix https://github.com/pop-os/shell/issues/859-- if I add a floating exception (app-wide or window only), then move an excepted window to another workspace with `Super+Shift+Down/Up`, the window tiles. As noted in the issue, this doesn't occur with manually-floated windows, only excepted windows.

**Comment by mmstick** [comment]
Will follow up on that

**Pull request merged**
