### PR TITLE
Update rebuild.sh

### PR DESCRIPTION
**Pull request by samuela**
So that there's a little space between "(y/n)" and the input prompt.

### CODE REVIEW

**Comment by mmstick** [comment]
Could you also fix the conditionals so that they aren't using `[[`? Since this is a feature of bash, and is not POSIX-compliant.

**Comment by samuela** [comment]
I'm not very familiar with this shell scripting stuff, what's the alternative to `[[ ... ]]`?

**Comment by mmstick** [comment]
`[[` is essentially equivalent to `test`

**Comment by samuela** [comment]
@mmstick Ok, done in https://github.com/pop-os/shell/pull/530/commits/8d930372ff1b4e02b980c16f9608e45b7c219c3b.

**Pull request merged**
