### PR TITLE
chore(exceptions): Add JavaEmbeddedFrame

### PR DESCRIPTION
**Pull request by sitiom**
Float tray icon of Java applications

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
Confirmed this works using JDownloader 2 as an example app. It's strange that the tray icon for apps using this framework show up as a black square in the actual tray and then float their actual icons over the desktop separately, but floating it makes more sense than allowing it to be tiled (it's tiny, non-resizeable, and not able to be interacted with.)

**Comment by jacobgkau** [comment]
Before:
Screenshot from 2022-08-24 14-49-07

After:
Screenshot from 2022-08-24 14-48-02

**Comment by sitiom** [comment]
> It's strange that the tray icon for apps using this framework show up as a black square in the actual tray and then float their actual icons over the desktop separately

It doesn't seem to be the case with Wayland however. The icon is properly displayed in the tray. Example with Megabasterd:
image

**Review by 13r0ck — APPROVED** [review]
Thanks!

**Pull request merged**
