### PR TITLE
fix(stacking): Now supporting workspaces-on-primary-display-only behavior

### LINKED ISSUE #645: Hidden windows in stack become visible behind transparent windows after workspace switch
**(1) Issue/Bug Description:**
My terminals have a small amount of transparency. Initially, if I stack terminals with another app, the other app does not show behind the terminal:
image

However, if I switch workspaces, then come back to this workspace, the hidden app shows itself behind the terminal suddenly:
image

**(2) Steps to reproduce (if you know):**

1. Open app in stacking mode
2. Add app with transparency to stack
3. Switch to another workspace
4. Switch back to original workspace

**(3) Expected behavior:**

Consistent appearance: Either apps in a stack always show or are always hidden

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```0.1.0~1602881205~20.04~a11d3c3```

**(7) Where was Pop Shell installed from:**
pop!_OS installation

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single laptop screen (1366 x 768)

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

### LINKED ISSUE #687: Stacked windows disappear on secondary monitor when switching workspaces
**(1) Issue/Bug Description:**

I have a dual monitor setup with the "Workspaces on primary display only" option on (I am mentioning this since I am not sure if that's the default behaviour for dual monitors or I modified it manually through Gnome-Tweaks).

When I stack windows on the secondary monitor and then switch to another workspace the stacked windows either disappear completely or only the "window tabs" disappear. If I switch back to the original workspace (where I have set the stacked windows up) they appear again and function as expected. (see demo video link below in (2))

I suspect it might be something to do with the focus of the window.

**(2) Steps to reproduce (if you know):**

Described above.

Additionally, here is a [demo video](https://youtu.be/hn4oi3OTL2k)(YouTube) I recorded of this bug.

**(3) Expected behavior:**

The stacked windows on the secondary monitor should stay visible and unchanged when switching workspaces.

**(4) Distribution (run `cat /etc/os-release`):**

 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```bash
$ gnome-shell --version
GNOME Shell 3.36.4
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```bash
$ apt policy pop-shell
pop-shell:
  Installed: 1.0.0~1603994289~20.04~ecc9b38
  Candidate: 1.0.0~1603994289~20.04~ecc9b38
  Version table:
 *** 1.0.0~1603994289~20.04~ecc9b38 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Came with the OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

2 Monitors:
- Primary (Horizontal): 2560x1080 [External Ultrawide monitor over DP]
- Secondary (Horizontal): 1920x1080 [Thinkpad T450s built-in display]

**(9) Other Installed/Enabled Extensions:**

Manually installed:

- ~`caffeine@patapon.info`~ (disabled)
- `desaturate_all@nicolas.brack.mail.be`
- `impatience@gfxmonk.net`
- `refresh-wifi@kgshank.net`
- `scroll-workspaces@gfxmonk.net`
- `sound-output-device-chooser@kgshank.net`
- `windowoverlay-icons@sustmidown.centrum.cz`

Built-in:

- `alt-tab-raise-first-window@system76.com`
- `always-show-workspaces@system76.com`
- `batteryiconfix@kylecorry31.github.io`
- ~`desktop-icons@csoriano`~ (disabled)
- `pop-shell@system76.com`
- `pop-shop-details@system76.com`
- `system76-power@system76.com`
- `ubuntu-appindicators@ubuntu.com`

**(10) Other Notes:**

Here's my hardware and system info from `neofetch`:
```
$ neofetch
             /////////////                kiro@dolores 
         /////////////////////            ------------ 
      ///////*767////////////////         OS: Pop!_OS 20.04 LTS x86_64 
    //////7676767676*//////////////       Host: 20BXCTO1WW ThinkPad T450s 
   /////76767//7676767//////////////      Kernel: 5.8.0-7625-generic 
  /////767676///*76767///////////////     Uptime: 3 days, 1 hour, 22 mins 
 ///////767676///76767.///7676*///////    Packages: 2677 (dpkg), 44 (flatpak), 36 (snap), 1 (appimaged) 
/////////767676//76767///767676////////   Shell: fish 3.1.0 
//////////76767676767////76767/////////   Resolution: 1920x1080, 2560x1080 
///////////76767676//////7676//////////   DE: GNOME 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-5600U (4) @ 3.200GHz 
    /////767676767676767676767/////       GPU: Intel HD Graphics 5500 
      ///////////////////////////         Memory: 5024MiB / 19717MiB 
         /////////////////////
             /////////////                                        
                                                                  
```

_Edit: add a list of built-in extensions, as well as the disabled extensions_

### PR DESCRIPTION
**Pull request by mmstick**
Closes #645 
Closes #687

### CODE REVIEW

**Comment by jacobgkau** [comment]
This does fix https://github.com/pop-os/shell/issues/687, but it does not fix https://github.com/pop-os/shell/issues/645. After switching workspaces, windows behind the active window in a stack show up behind the active window when it's partially transparent:

Screenshot from 2020-11-09 15-27-25

It makes sense to me to see other windows since they're supposedly "stacked" on top of one another, but if the transparency doesn't show the second window initially, that shouldn't change when the workspace is changed.

**Comment by mmstick** [comment]
Had to settle for a workaround. Something in GNOME Shell is unhiding hidden window actors on a workspace switch, at a random time after it issues the active-workspace-changed signal.

**Comment by jacobgkau** [comment]
I'm having trouble with minimizing not working reliably. (I know minimizing isn't something we encourage, but it is part of regression testing.) It sometimes doesn't work and sometimes moves the window to another part of the screen instead of hiding it. Sometimes it does work. https://www.dropbox.com/s/gqhmc7mtqat8hch/simplescreenrecorder-2020-11-10_11.59.51.mp4?dl=0

**Comment by mmstick** [comment]
These changes only affect stacked windows. Does this affect master as well?

**Comment by mmstick** [comment]
Not seeing any minimize issues from this branch

**Comment by jacobgkau** [comment]
I did further testing on the minimize issue, and while I wasn't able to recreate that specific issue again, I was able to create a different one on both this branch and master. I've opened https://github.com/pop-os/shell/issues/706 for that, and I'll continue with testing this knowing that issue isn't a regression.

**Review by jacobgkau — APPROVED** [review]
Regression testing passed. Ran through it once with `workspaces-on-primary-display-only` and once with the default setting of workspaces spanning all displays.
[shell-pr697-workspace-primary.txt](https://github.com/pop-os/shell/files/5525594/shell-pr697-workspace-primary.txt)
[shell-pr697-workspace-all.txt](https://github.com/pop-os/shell/files/5525520/shell-pr697-workspace-all.txt)

**Comment by mgamigo** [comment]
I experience the same behaviour, should it be fixed by any update?

**Pull request merged**
