### PR TITLE
fix: Autotile keyboard resize behavior is now consistent

### PR DESCRIPTION
**Pull request by mmstick**
Left / Right and Up / Down will now always decrease / increase. Position of a window will no longer dictate how it will resize.

### CODE REVIEW

**Comment by mmstick** [comment]
Found an issue with this. Fixing it

**Comment by Serkan80** [comment]
When I float an app in autotile mode, I cannot move it with my arrows keys. 
When I do that, it swaps with apps. 
And when I try to resize it, the app goes back into non floating mode and then the resizing starts the apply.

**Comment by leviport** [comment]
@Serkan80 Thanks for the report. We're tracking that here: https://github.com/pop-os/shell/issues/155

**Comment by mmstick** [comment]
Closing this because the fix I'm doing for reflows will also be fixing this.

**Pull request closed without merging**
