### PR TITLE
fix: Do not unstack stack on last remaining window

### LINKED ISSUE #1301: Last stacked window gets unstacked automatically
When I close out of the second to last window in a stack the last remaining window is left unstacked. This is very aggravating as I have to create a new stack every time I open a new window. Otherwise the new window is not stacjed and is instead tiled as it would be normally. 

Here is a previous issue citing the same occurrence:

I can confirm this; the last window remains in stack mode if you remove the penultimate window from the stack, however closing that window destroys the stack. 

Unfortunately the commit doesn't fix the issue. 

-- bvs

_Originally posted by @bettyvschmartz in https://github.com/pop-os/shell/issues/881#issuecomment-886538473_

### PR DESCRIPTION
**Pull request by mmstick**
Closes #1301

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The behavior's now inconsistent when dragging a window out of a stack with the mouse. When the window is dropped into the same tree, then the remaining window is still unstacked; when the window is dropped into a different tree, then the remaining window is not unstacked.

https://user-images.githubusercontent.com/7199422/156460032-2e051642-56b0-4b90-939b-e99c387f12ac.mp4

Is there any way to make this more predictible? If we're wanting to not unstack the last window, then it shouldn't be getting unstacked in any of the three operations shown above.

**Comment by mmstick** [comment]
@jacobgkau Fixed it. A drag out of a stack won't auto-unstack the remaining window now.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
df0ba04 fixed the issues I showed in the video before; the stack is no longer destroyed in any of those cases.

However, I am not able to destroy a stack with Super-S, which is a bigger regression. Once I put a window into a stack using mouse or keyboard, the stack is stuck there. Trying to move the last window out of the stack with window management mode + arrow keys also does not work.

**Comment by mmstick** [comment]
Okay. Found the correct code to remove to keep unstacks by keyboard and management mode working.

**Pull request merged**
