### PR TITLE
fix(tiling): Windows launching onto window that isn't focused

### LINKED ISSUE #1166: Incorrect fork order
**(1) Issue/Bug Description:**

Left tile gets split before right tile. See video:

https://user-images.githubusercontent.com/4994123/132470707-5b122c88-fca5-41a5-a9f4-db40c82250f8.mp4

May be related to https://github.com/pop-os/shell/issues/1137

**(2) Steps to reproduce (if you know):**

Open 3 terminals:
1. First is full screen
2. Second splits vertically - left / right
3. Third splits the left terminal vertically

Window focus doesn't matter - even if I focus another window, the fork order remains the same. I've tried on Wayland and X11.

**(3) Expected behavior:**

I would expect the right side to split first, such as in the video here: https://github.com/pop-os/shell/pull/1148#pullrequestreview-737572111 (but with a horizontal split on the right fork)

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1630345490~21.04~0484ffb
  Candidate: 1.1.0~1630345490~21.04~0484ffb
  Version table:
 *** 1.1.0~1630345490~21.04~0484ffb 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3440 x 1440 single monitor.

**(9) Other Installed/Enabled Extensions:**

Screenshot from 2021-09-08 19-55-40

### PR DESCRIPTION
**Pull request by mmstick**
Closes #1166

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
The wording in https://github.com/pop-os/shell/issues/1137 seems to imply that windows should quarter-tile first. After this change, I am now seeing the "incorrect" behavior of new windows continuing down the same side of a fork instead of alternating back to quarter tile:

https://user-images.githubusercontent.com/7199422/132879019-0a827345-50a8-4bbd-b7ea-cbd0a222539c.mp4

This behavior does seem logical, but we need clarification on what the expected behavior is.

**Comment by mmstick** [comment]
Windows should always launch onto the window that is focused, so you can expect to know where the window is tiled.

**Comment by jacobgkau** [comment]
I understand, https://github.com/pop-os/shell/issues/1137 is just referring to the split happening horizontally instead of vertically.

**Comment by jackpot51** [comment]
@jacobgkau this behavior in this PR is the correct behavior as far as I know. A new window should always halve the focused window, or join the focused window's stack.

**Comment by jacobgkau** [comment]
I'm seeing cases across multiple displays where a new window is not joining a focused window:

https://user-images.githubusercontent.com/7199422/132885047-13fbd713-707e-44d4-bc85-765bf9adb62a.mp4

I believe the key to recreating this is switching between several stacked windows just before switching focus to another display and opening a new one.

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The stacking case from before is fixed. However, I'm still seeing new windows appear on the non-focused display if the mouse cursor is on the non-focused display. (Basically, the cursor seems to override focus for choosing which display to use.)

https://user-images.githubusercontent.com/7199422/133280607-859e9920-ae16-43f1-8684-48f2fcdd0f91.mp4

Is this how it's supposed to work? It seems incorrect based on the description of "should always launch onto the window that is focused."

**Comment by mmstick** [comment]
It should be the active window that matters more than the mouse position. Will look

**Comment by jacobgkau** [comment]
That commit fixed the remaining issue with window opening in tiled mode. Windows now always open on the focused window/stack, regardless of cursor position.

However, it introduced a change of behavior when entering tiling mode; all windows now tile onto the primary display. Before:

https://user-images.githubusercontent.com/7199422/133296022-4e23540a-9eab-4087-94ae-d4a4bfa8ca65.mp4

After:

https://user-images.githubusercontent.com/7199422/133295750-db1bb67f-7938-4a39-a616-749aff209206.mp4

Can existing windows be tiled onto their current display when entering tiling mode, without changing the behavior for opening new windows?

**Comment by mmstick** [comment]
Sure. Done.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Everything looks good now. Regression testing passed:
[shell-pr1171-hirsute.txt](https://github.com/pop-os/shell/files/7163914/shell-pr1171-hirsute.txt)
[shell-pr1171-focal.txt](https://github.com/pop-os/shell/files/7164104/shell-pr1171-focal.txt)

**Pull request merged**
