### PR TITLE
fix: check primary monitor workspace, no reflow

### LINKED ISSUE #246: Unable to move a window to a second monitor that has a floating window on it
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
``` 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Moving windows to other screens is inconsistent when the second screen has a floating window on it. Moving with either adjument mode, or just using Super+Shift+Left/Right doesn't do anything.

**Steps to reproduce (if you know):**
Dual monitor setup, open a window on one monitor and set it to floating, and try moving another window from the other monitor with keybindings.

**Expected behavior:**
Windows should move seamlessly between monitors even if the second monitor contains any active floating windows.

**Other Notes:**
Moving with the mouse works as expected, and it seems like the only workaround as of right now.

### LINKED ISSUE #522: "move window one monitor to the right/left" doesn't work with tiling enabled
**Distribution (run `cat /etc/os-release`):**

```
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

gnome-shell-extension-pop-shell-0.1.0-0.2.20200821git8416328.fc32.noarch (built from commit 8416328 in [COPR](https://copr.fedorainfracloud.org/coprs/carlwgeorge/gnome-shell-extension-pop-shell/))

**Issue/Bug Description:**

Moving a window one monitor to the left or right via the keyboard shortcut does not work with tiling enabled.  The window does initially move as instructed, but immediately returns to the monitor it started on.  This is reproducible in a Pop!_OS live environment as well, so I don't believe it's a problem with the RPM packaging.  Here is a video of the behavior.

https://imgur.com/RpuI3xp

**Steps to reproduce (if you know):**

1. enable tiling mode
2. create one or more windows on the first monitor
3. press `<Shift><Super>Right` to move a window to the second monitor

**Expected behavior:**

window moves to second monitor and stays there

### PR DESCRIPTION
**Pull request by jmmaranan**
Do not reflow when workspace primary is disabled. 

Hopefully: 
- Fixes #522
- Fixes #246 - looks like a dupe of 522 or vice versa

I do not have 3 monitors.
Need testing on primary, secondary, secondary or secondary, primary, secondary setups.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by jacobgkau** [comment]
The keyboard shortcuts to move windows between displays still don't work as expected with tiling enabled after this change.

With two displays of different sizes, and the primary display being the smaller one, I can move a window from primary to secondary using Super-Shift-Right, but not back the other way with Super-Shift-Left: https://www.dropbox.com/s/gvyqzqbf21yw4jj/shell-pr528-screencast2.webm?dl=0 

As you can see, when I try to move from the larger secondary display to the smaller primary display, the window moves a few pixels. Once that happens, it doesn't move any farther when I try pressing Super-Shift-Right/Left again; I need to enter adjustment mode to get it un-stuck.

Here's a three-display example where the primary display (center) is one of the larger displays: https://www.dropbox.com/s/20dw3pdpk0cqr65/shell-pr528-screencast6.webm?dl=0 

- The window gets stuck when moving from a secondary display to a primary display of the same size (which has less usable space due to the top bar.)
- When I enter adjustment mode and press the left arrow key once, the window moves all the way to the left-most display, which suggests that Shell thought the window was on the center display at that point (even though it looked like it was still on the right-most display.)

In this layout, I'm able to move between the three displays successfully because the center display is tiling the windows small enough to fit on either of the side displays: https://www.dropbox.com/s/gcsa14tho7ydn1t/shell-pr528-screencast5.webm?dl=0 

Since I can see in that last video that the window's being moved to a smaller display before it's being resized, that makes me think the top bar is the only thing preventing the window from being moved in the other cases.

**Comment by jmmaranan** [comment]
Thanks @jacobgkau - the top bar or panel on the primary is what seems to be blocking the windows from moving. If the panel is displaying across all windows (Dash-To-Panel), it works on two monitors. 

Would you be able to try the test cases in a 3 monitor setup with any extension that spans the Panel across monitors? I will try also this in a built-in display and 2 monitors. Waiting for the USB-to-USB-C adapter.

Another thing is that this looks like a standard Mutter or Gnome-Shell, `move windows to monitor` functionality based on the keybindings, so this might be a bug upstream.

**Comment by jacobgkau** [comment]
> Would you be able to try the test cases in a 3 monitor setup with any extension that spans the Panel across monitors?

With three monitors and Dash to Panel, the issue occurs when going from a larger display to a smaller display. The window does shift up (away from the panel) instead of down: https://www.dropbox.com/s/h2lw6snwsyqohh3/shell-pr528-screencast7.webm?dl=0 
 
> Another thing is that this looks like a standard Mutter or Gnome-Shell, `move windows to monitor` functionality based on the keybindings, so this might be a bug upstream.

I think you're correct. After disabling the Pop Shel extension and restarting the shell, I'm able to reproduce the issue. Large and small display: https://www.dropbox.com/s/cwwze9t7x3qbqvr/shell-pr528-screencast8.webm?dl=0 

Two large displays: https://www.dropbox.com/s/ufw9x8gtkghfelf/shell-pr528-screencast9.webm?dl=0 

As you can see, the issue doesn't occur until the window is nearly filling up the source display. The issue also doesn't occur when a window is maximized. It seems Pop Shell is exposing this bug more prominently because it makes it very easy/common to have a window take up almost an entire display (with less than a panel's worth of gap), but not be maximized.

I see the following upstream issues open for this:

https://gitlab.gnome.org/GNOME/mutter/-/issues/455 

https://gitlab.gnome.org/GNOME/mutter/-/issues/477 

As a side note, it doesn't seem entirely incorrect for GNOME to refuse to move a window to a display where it's not going to fit, although that's inconsistent with being able to move a window to a smaller display when there's not a panel in the way.

**Comment by mmstick** [comment]
It's definitely a GNOME Shell issue, because `<Super>Shift`-based movements are native GNOME Shell keyboard shortcuts, and we don't have much control over the code they execute for these actions.

**Comment by jmmaranan** [comment]
@jacobgkau - your observations seem to be correct. Without the tiling, the window is moved to the same allocation/coordinates as of the previous monitor and scaled by the Window Manager if they are in different resolutions.

@mmstick - I think binding the keyboard to Pop Shell's window management left and right movement will fix this in the time being if we would want the functionality to be seamless. Or a vanilla implementation of the windowmanagement left/right. Thoughts?

**Comment by mmstick** [comment]
Having our own implementation of moving windows across monitors would be the way to go, and doing away with the bindings to GNOME's. Only way to be sure we have control over how windows move around workspaces and displays.

**Comment by jmmaranan** [comment]
@mmstick - then the current change only fixes moving out to a monitor that it thinks it can accommodate the current window allocation. Putting this in DRAFT or WIP.

**Comment by mmstick** [comment]
Moving windows between monitors should be fixed now. Windows are shrunk to find on the monitor they're moved to if they happen to be too large for the monitor.

@jmmaranan Could you rebase these changes onto stacking_focal?

**Comment by jmmaranan** [comment]
@mmstick - just to be sure, had put this on #543

**Pull request closed without merging**
