### PR TITLE
Dev Rollup

### LINKED ISSUE #373: modal dialogs stay on top of other apps even when not using tiling mode
-->

**Distribution (run `cat /etc/os-release`):**

`Pop!_OS 20.04 LTS`
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

pop-shell:  `0.1.0~1589754807~20.04~e5f3b4d`

**Issue/Bug Description:**

All modal dialogs are set to "always on top" by default when the extension is enabled despite not using the tiling mode. When switching to a different app it stays on screen and when i try to move it, it brings its parent window to focus.

**Steps to reproduce (if you know):**

example:
1-open files
2- open the about files modal dialog
3-switch to other window/app
4-the about file modal dialog stays on top

**Expected behavior:**

modal window to stay on top of its parent window when not using tiling mode

**Other Notes:**

Screenshot from 2020-05-19 18-50-40

https://www.reddit.com/r/pop_os/comments/gmbv8c/modal_dialogs_always_on_top_is_this_a_bug/

Edit: added reddit post that has video of the issue

### LINKED ISSUE #602: Stacked windows appear if tiling is disabled while on a different workspace
**(1) Issue/Bug Description:** If I stack a window, move to another workspace, and then disable tiling, the formerly-stacked window incorrectly appears on the current workspace (it's not actually on this workspace, and I can't interact with it; it disappears next time I move between workspaces.)

**(2) Steps to reproduce (if you know):**
1. Enable tiling.
2. Create a stack.
3. Move to a different workspace.
4. Disable tiling. (If the current workspace is not empty, move any windows out of the way.)

**(3) Expected behavior:** The formerly-stacked window should only appear on its own workspace.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS

**(5) Gnome Shell version:** `3.36.4-1ubuntu1~20.04.2pop1~1597874448~20.04~260a1a7`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** Happens on:
- Master branch (`50d953a`)
- "Static" branch (`bd7b213`)
- Currently released version (`ff702bc`)

**(7) Where was Pop Shell installed from:** Pop PPA

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1 x 1080p

**(9) Other Installed/Enabled Extensions:** N/A

**(10) Other Notes:** Video: https://www.dropbox.com/s/j5bxu73vxoeeay6/shell-pr601-issue-screencast1.webm?dl=0

### PR DESCRIPTION
**Pull request by mmstick**
This is a rollup of all rebased PRs onto the dev branch.

To be rebased onto master when regression tests pass

Closes #602
Closes #373

### CODE REVIEW

**Comment by leviport** [comment]
Do we want to throw this one in too? https://github.com/pop-os/shell/pull/607

**Comment by mmstick** [comment]
Yes, you can do testing on this whenever you feel ready to. I'll pile on each approved PR as they're approved

**Review by leviport — APPROVED** [review]
Everything is looking good on this rollup so far: [shell-dev-rollup-614-checklist.txt](https://github.com/pop-os/shell/files/5344009/shell-dev-rollup-614-checklist.txt)

I can re-test with https://github.com/pop-os/shell/pull/615 and https://github.com/pop-os/shell/pull/616 if we want to throw those in too.

**Comment by mmstick** [comment]
I'll merge these and others can be done later.

**Pull request merged**
