### PR TITLE
feat: Add smart gaps feature

### LINKED ISSUE #470: [Feature Request] Smart-gaps
A behaviour similar to smart-gaps in i3-gaps which when there's only one window/program open in a workspace, it fills the whole space without any gaps, when another program/window is started then the gaps are shown.

**Expected behaviour**:
1. If there's only one program in the workspace, the program's window is in maximized mode
2. When there's any other program, the gaps appears.

### PR DESCRIPTION
**Pull request by mmstick**
Which shall be disabled by default, but is a common request

Closes #470

### CODE REVIEW

**Comment by mmstick** [comment]
@jacobgkau Fixed now

**Comment by jacobgkau** [comment]
@mmstick Is what's shown in this video expected behavior? https://www.dropbox.com/s/h3hdigjn5qsjnee/shell-pr484-video1.mkv?dl=0 

Based on #470 and the preference description, I was expecting smart gaps to only kick in if a window is the only window on a workspace/display. If the intention is to never have gaps on the outer edge, then I'm not understanding why moving the terminal between these two positions would cause the gaps to appear and disappear.

**Comment by mmstick** [comment]
@jacobgkau I found the problem

**Comment by leviport** [comment]
@mmstick did that last commit need to be tested before merging?

**Comment by laichiaheng** [comment]
I still see the gap with only one window.

**Comment by mmstick** [comment]
Is the AUR building from the master branch?

**Comment by laichiaheng** [comment]
@mmstick It is from master_focal

**Comment by mmstick** [comment]
It works here, so either you haven't restarted the shell, or it didn't build the latest commit.

**Comment by laichiaheng** [comment]
> It works here, so either you haven't restarted the shell, or it didn't build the latest commit.

Nope. I have re-installed it and restart the shell many times.

**Comment by mmstick** [comment]
It's working in Pop!_OS

Screenshot from 2020-08-11 20-43-14

**Comment by laichiaheng** [comment]
> It's working in Pop!_OS
> 
> Screenshot from 2020-08-11 20-43-14

It appears now.

**Pull request merged**
