### PR TITLE
feat(plugin-recent): Initially sort results by last opened

### LINKED ISSUE #785: recent documents are listed in strange order
**(1) Issue/Bug Description:**
* when I try to open a recent documents auto complete list filling in a way that it may consider file type or the application that used to open the file.
* for example if I'm playing mp3 files from a playlist these are listed at top. even though I open a text file that will do to the bottom.

**(2) Steps to reproduce (if you know):**
* pop key + /
* d:

**(3) Expected behavior:**
* last opened file should be at top, whatever the file type or program is active.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**(5) Gnome Shell version:**
* 3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
Name         : gnome-shell-extension-pop-shell
Version      : 1.0.0
Release      : 3.20201130gitee943b8.fc33
Architecture : noarch
Size         : 900 k
Source       : gnome-shell-extension-pop-shell-1.0.0-3.20201130gitee943b8.fc33.src.rpm

**(7) Where was Pop Shell installed from:**
* installed using dnf command from the repository README

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by mmstick**
Close #785

### CODE REVIEW

**Review by ids1024 — APPROVED** [review]

**Comment by jacobgkau** [comment]
The results used to be sorted in alphabetical order (which didn't make sense for a recents list.)

After the change, the results seem to be sorted in order of most recently created to least recently created. For example, in this list with three text files and a screenshot, I created there of the text files first, took a screenshot, then created the fourth text file:

Screenshot from 2021-01-06 15-36-06

Neither opening up one of the text files (via Nautilus, Activities, or the launcher) nor modifying/saving it brings it to the top of the list. Deleting a text file and creating a new one with the same name also does not change its place in the list. This is definitely an improvement, but is this the intended behavior?

**Review by bflanagin — COMMENTED** [review]
The issues @jacobgkau mentioned seems fixed in latest version. The files now change order when opened or edited as expected. I think its ready for approval, unless anyone has objections.

**Review by bflanagin — APPROVED** [review]

**Comment by jacobgkau** [comment]
Hmm, I'm still seeing results sorted by creation time instead of modification or last opened. For example, I made a new file called `document-2.txt` this morning, and here's a screencast of me opening, modifying, and saving it, then still having it sorted lower in the list than several other files: https://www.dropbox.com/s/2szpzazgp443nyv/shell-pr811-screencast1.mkv?dl=0 

Does the launcher use a GNOME mechanism for this where the issue could be somewhere else?

**Comment by bflanagin** [comment]
Strange, this is whats happening on mine.

https://drive.google.com/file/d/1LShIbduAaeNQs0MTlyeQTV8vdbNDeLop/view?usp=sharing

 Will do a little more digging to see if I can replicate the inconsistency.

**Review by bflanagin — CHANGES_REQUESTED** [review]
Sorry for the confusion, I miss understood what we were testing, Jacob is right, its still not working.

**Pull request closed without merging**
