### PR TITLE
fix: Use Gio.AppInfo.get_all for app list

### LINKED ISSUE #293: Launcher showing duplicate entries while Activites does not (Extensions, specifically)
**Distribution (run `cat /etc/os-release`):**
 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
$ apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1588624471~20.04~dfb378c
  Candidate: 0.1.0~1588624471~20.04~dfb378c
  Version table:
 *** 0.1.0~1588624471~20.04~dfb378c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When I search for the new Extensions application using the pop-shell launcher, it see two entries: one which woks and one does not. Activities only shows one.

pop-shell launcher:

image

Activities search:

image

**Steps to reproduce (if you know):**
Search for "extensions" using both pop-shell launcher (Super+/) and Activities (Super).

**Expected behavior:**
There shouldn't be duplicate entries.

### PR DESCRIPTION
**Pull request by scaryrawr**
- should_show and other hidden modifiers did not appear to work when loading files manually to hide from launcher
- Remove search directories
- Use [Gio.AppInfo.get_all()](https://gjs-docs.gnome.org/gio20~2.64p/gio.appinfo#function-get_all) for getting apps, should work with all installers that register with the system

fixes #293 .

### CODE REVIEW

**Comment by scaryrawr** [comment]
The text being displayed is now changed since it's not using the search paths:

image

**Comment by scaryrawr** [comment]
Duplicates no longer showing:
image

**Comment by mmstick** [comment]
Does this work for Flatpaks and Snaps, too?

**Comment by scaryrawr** [comment]
> Does this work for Flatpaks and Snaps, too?

It works for both (I have Glimpse as a flatpak and Caprine as a Snap installed), as well as AppImages (but I think I have appimaged installed to register them).

The comments being shown can get a bit long and get truncated often though.

**Comment by scaryrawr** [comment]
Ah, @mmstick it looks like you already fixed it another way with handling duplicates.

**Comment by mmstick** [comment]
Only problem I have with this is that the results don't show that they are from a Flatpak source, since it's possible that a person may have a deb and flatpak version installed at the same time.

**Comment by scaryrawr** [comment]
> Only problem I have with this is that the results don't show that they are from a Flatpak source, since it's possible that a person may have a deb and flatpak version installed at the same time.

Agree, I was wondering if there's a way to get the install source but didn't see any in the APIs.

**Pull request closed without merging**
