### PR TITLE
Port to Gnome 45

### LINKED ISSUE #1649: Gnome 45 support
**(1) Issue/Bug Description:**
Pop Shell is not compatible with Gnome 45, it's probably related to the ESM switch https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm 

```
import declarations may only appear at top level of a module
```

**(2) Steps to reproduce (if you know):**
Upgrade to Gnome 45

**(3) Expected behavior:**
should work

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME="Fedora Linux"
VERSION="39 (Workstation Edition Prerelease)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**
45

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```gnome-shell-extension-pop-shell-1.2.0^11.b5accce-2.fc39.noarch```

**(7) Where was Pop Shell installed from:**
Fedora repo

### PR DESCRIPTION
**Pull request by matrv**
Closes #1649

Changed the build config to output ESM format, fixed all errors to make it work on gnome 45. Sadly, this makes in incompatible with the older gnome versions.

Sorry, I forgot I had autoformatting turned on in my editor. Some code got formatted.

This is my first serious contribution to a gnome extension, sorry if I missed something.

### CODE REVIEW

**Review by mmstick — CHANGES_REQUESTED** [review]
Not backwards compatible. This breaks the jammy build.

**Comment by jacobgkau** [comment]
Should we set up a different target branch for future versions since GNOME 45 extensions aren't backwards-compatible? (It may not have CI yet since we don't have CI for mantic, but I assume we'll want to set that up anyway for system76-driver, etc.)

**Comment by mmstick** [comment]
We could potentially merge it into a new branch

**Comment by Artofaj** [comment]
@jacobgkau Thank you so much for taking the time for this PR!

**Comment by jackpot51** [comment]
We do have CI for 23.10, if we want to put this in a `master_mantic` branch.

**Comment by mmstick** [comment]
Then I'll create a mantic branch and merge this there

**Pull request merged**
