### PR TITLE
fix: active-hint updates

### LINKED ISSUE #214: Active hint remains on when you exit full-screen video
**Distribution (run `cat /etc/os-release`):**
 
 Fedora 32, Gnome 3.36, Xorg
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

901dcbccfc22dd5153235036aa41c01269234309

**Steps to reproduce (if you know):**
1. Maximize browser
2. Play Youtube/Netflix etc, maximize video window
3. Press Escape, which will quit maximized window but still remain with the browser maximized.
4. Active hint is now stuck on screen.

### LINKED ISSUE #427: Active hint moves underneath all windows when floated window is moved between workspaces
**Distribution (run `cat /etc/os-release`):** `Pop!_OS 20.04 LTS`
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
`0.1.0~1592240829~20.04~3e18f75` and `0.1.0~1591631045~20.04~830dd7a`.

**Issue/Bug Description:** When a window is floated and then moved between workspaces, the active hint goes underneath all windows.

**Steps to reproduce (if you know):**
1. Enable the active hint. If in tiling mode, float a window (Super-G). The issue also occurs when not in tiling mode.
shellbug1
shellbug2

2. Move the window to the next workspace (Super-Shift-Down.) Notice that the hint becomes thinner (as it's now behind the active window.)
shellbug3

3. Move the window back to the previous workspace (Super-Shift-Up.) Now the hint is nearly invisible since it's covered up by the windows in the background.
shellbug4

**Expected behavior:** Active hint should always be displayed on top so it's visible when enabled.

### LINKED ISSUE #452: active tile hint has different z-order than window it surrounds
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1593273798~20.04~9e8ab29
  Candidate: 0.1.0~1593273798~20.04~9e8ab29
  Version table:
 *** 0.1.0~1593273798~20.04~9e8ab29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

the active tile hint has a different z-order than the window it is surrounding.  

**Steps to reproduce (if you know):**

1. launch PyCharm
1. launch Headset
1. set Headset to be always on top
1. try to write code in PyCharm

**Expected behavior:**

You should, if possible, use the same z-order as the window you are surrounding.  

Additionally, listening for z-order changes to that window may be necessary.  Imagine if the user right clicked on the title bar and selected "Always on top" for example.

**Other Notes:**

Screenshot from 2020-07-08 10-03-44

Shows PyCharm tile below is active but Headset has "Always on top" set.  Notice how the z-order is above the always on top and not matching the window in the active tile, PyCharm.

### PR DESCRIPTION
**Pull request by jmmaranan**
Issue fixes:
- Closes #452
- Closes #427
- Fixes #214

Updates:
- Use the window-clone-border for now to update the color when the theme changes. Putting the active-hint css in the local `dark` or `light` css files does not seem to toggle the color when changing themes.

### CODE REVIEW

**Comment by jmmaranan** [comment]
A reboot while this branch is installed causes GDM to crash

**Comment by jmmaranan** [comment]
Re-installed Pop!OS using the Nvidia 20.04 ISO, was using 19.10 and did the pop-upgrade. And the freezing seemed to have went away. The journal does not tell anything.

**Review by mmstick — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Confirmed https://github.com/pop-os/shell/issues/427 is fixed.

[shell-pr515.txt](https://github.com/pop-os/shell/files/5189633/shell-pr515.txt)

**Comment by mmstick** [comment]
I've cherry-picked all the commits from this branch to master

**Comment by jmmaranan** [comment]
Awesome thanks @mmstick

**Pull request closed without merging**
