### PR TITLE
feat: Floating window config dialog

### LINKED ISSUE #513: GUI for adding windows to the floating list
Pop shell does not always correctly identify whether a window should tile.  E.g. pop-ups should typically not tile. If the program that generates a pop-up correctly identifies it as such, then Pop-Shell (correctly) does not tile them.  However, some software generates pop-ups that are not identified as such.  It is extremely useful for the user to be able to specify their desired behaviour for these windows.

Looking through the source code I discovered that Pop-shell does read window-specific rules from a file config.json.  Using this I was able to generate by trial and error a json file that sets the "window_shall_float" flag to false for a specified window title.

However, this ability to blacklist windows from tiling is not documented.  A useful improvement to Pop-shell would be to either document clearly how users can edit the config file for themselves, or (better) provide a UI interface to choose whether to blacklist a window by adding it to this config. 

My config.json file now looks like this:

```
{
  "float": [
    {
      "class": "Zotero",
      "title": "Quick Format Citation"
    }
  ],
  "log_on_focus": false
}

```

### PR DESCRIPTION
**Pull request by mmstick**
Closes #513

### CODE REVIEW

**Comment by WatchMkr** [comment]
@mmstick is it possible to add a float application window option to g-c-c > Applications instead? I'm leery of introducing a pattern of launching configuration applications from the panel. It gives the feeling of an extension to the operating system rather than an integrated component.

**Comment by mmstick** [comment]
@WatchMkr It's not because there's no association between applications and their windows. `Meta.Window` doesn't have any information about what `.desktop` file opened it.

**Review by jacobgkau — CHANGES_REQUESTED** [review]
The "title" and "class" boxes (or headers) seem to be reversed from the entries in the config file:

shell-pr580-screenshot1

That's what I'm requesting changes for.

Also, do we need any UX input for the dialog? It seems like there's a lot of spacing between the headers at the top, the + sign doesn't have any sort of hover effect like a normal button would (neither do the trash can icons), and the + sign seems awfully close to the text boxes above it.

Do we want to have a checkbox (or on/off switch) to enable/disable log-on-focus? Right now, I still had to manually edit the config file to toggle log-on-focus to see what class I needed to use. Are we expecting people to generally have that information without needing to use log-on-focus? (It would be even better if we could click a window to populate its class and/or title into the dialog, eliminating the terminal from this feature's flow altogether, but not sure what's possible.)

**Comment by mmstick** [comment]
There's also the matter if we could tell what .desktop a window is associated with, we probably don't want every window from that application to float.

**Comment by mmstick** [comment]
Yes, UX input from @maria-komarova  would be good. Although I think our shell theme may be choosing that spacing.

**Comment by WatchMkr** [comment]
@mmstick how about an Always Floating option in the context menu when right-clicking a window?

**Comment by mmstick** [comment]
Might be possible. Looked into it before but I couldn't figure out how. Anyone know of any gnome shell extensions that add context menu options?

**Comment by WatchMkr** [comment]
> There's also the matter if we could tell what .desktop a window is associated with, we probably don't want every window from that application to float.

Do we have an override list that I can review?

**Comment by mmstick** [comment]
Defaults are here: https://github.com/pop-os/shell/blob/master_focal/src/config.ts#L18

**Pull request closed without merging**
