### PR TITLE
feat: Replace JS launcher service with Rust launcher service

### LINKED ISSUE #199: Feature Request: Execute aliased commands from launcher
Currently when trying to execute a command by an alias i defined in my .bashrc file, I get *Command not found*

### LINKED ISSUE #849: Launcher does not learn on my system
**(1) Issue/Bug Description:**
Launcher does not learn preferred commands

**(2) Steps to reproduce (if you know):**
Start an app multiple times does not reduce the keys necessary to make app default selection

**(3) Expected behavior:**
After multiple starts typing "f" should default select "firefox"
This works is how the Kupfer Launcher works. 

**(4) Distribution (run `cat /etc/os-release`):**
 VERSION="20.04.1 LTS (Focal Fossa)"

**(5) Gnome Shell version:**
3.36.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
github

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

### LINKED ISSUE #903: Misbehaving launcher plugins freeze shell
**(1) Issue/Bug Description:**

A launcher plugin which (due to some internal error perhaps) does not reply to a `query` event, by simply not writing anything to stdout, freezes the launcher and the entire shell so definitely that (on wayland at least) I had to resort to a SysRq reboot.

I presume the launcher actually runs in-process as part of the shell extension.

I think this is rather dangerous; even a slight error in the communication between a plugin and the launcher can bring down the entire Gnome Shell, which is catastrophic on Wayland where the shell is also the compositor process (arguably a serious design flaw in Gnome, but that's what we've got :shrug: :confused: )

Perhaps Pop Shell could move the launcher into a dedicated subprocess? I understand that this may not be possible though, if the launcher needs access to the St toolkit or Gnome Shell API :confused: 

**(2) Steps to reproduce (if you know):**

**WARNING: After installing the plugin below using the launcher will likely freeze your desktop session!**

```
$ mkdir -p ~/.local/share/pop-shell/broken
$ cat > ~/.local/share/pop-shell/broken/meta.json <<EOF
{
    "name": "broken",
    "description": "Demonstrate broken",
    "pattern": ".*",
    "exec": "broken.py",
    "icon": "dialog-error"
}
EOF
$ ~/.local/share/pop-shell/broken/meta.json <<EOF
import sys
for line in sys.stdin:
  pass
EOF
```

**WARNING: The next steps may leave your system in a state where only a Sysrq reboot or hard reset helps; best use a VM for this!**

Logout and login again to make Pop Shell discover the launcher, then type `Ctrl+/` and type any text.  The shell freezes :bomb: 

**(3) Expected behavior:**

The shell handles unresponsive launcher plugins gracefully.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**(5) Gnome Shell version:**

```
$ pacman -Qi gnome-shell | head -n3
Name            : gnome-shell
Version         : 1:3.38.3-1
Description     : Next generation desktop shell
```

**(6) Pop Shell version**

```
$ pacman -Qi gnome-shell-extension-pop-shell | head -n3 
Name            : gnome-shell-extension-pop-shell
Version         : 1.2.0-2
Description     : Pop Shell - Tiling window management in Gnome (WIP)
```

**(7) Where was Pop Shell installed from:**

<https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell>

Which essentially comes down to `make install`:

```
     make DESTDIR="${pkgdir}/" install
	install -Dm644 schemas/org.gnome.shell.extensions.pop-shell.gschema.xml -t \
		"$pkgdir/usr/share/glib-2.0/schemas"
	install -Dm644 keybindings/*.xml -t \
		"$pkgdir/usr/share/gnome-control-center/keybindings"
    install -Dm755 scripts/configure.sh "${pkgdir}/usr/share/gnome-shell/extensions/pop-shell@system76.com/scripts/configure.sh"
```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

Built-in laptop screen:

image

**(9) Other Installed/Enabled Extensions:**

```
$ gnome-extensions list --enabled 
appindicatorsupport@rgcjonas.gmail.com
vscode-search-provider@jomik.org
jetbrains-search-provider@swsnr.de
nasa_apod@elinvention.ovh
native-window-placement@gnome-shell-extensions.gcampax.github.com
pop-shell@system76.com
```

**(10) Other Notes:**

I'd like to take the opportunity to give my heartfelt thanks to you for this magnificent extension :pray: It gives Gnome almost everything I missed from i3, while being so super-easy to setup, and rock-solid (till now it never crashed on me :clap: )  It's a great piece of work and I am very grateful that you give this to the community of Gnome users :pray: 

Thank you very much :heart:

### LINKED ISSUE #995: Feature parity of launcher with gnome activities overview search
Previously, the old _activities overview_ would show workspaces and seamlessly switch to searching apps, settings and files once the user started typing. With the launcher being established as the new one-stop-shop for all those activities, I am trying to incorporate it more and more into my workflow. However, I find myself having to go back to the regular gnome search for certain search results. As such, here is my wishlist for the launcher:

- [ ] Searching files and folders that have not very recently been opened: For example, when I search `hello` in the gnome search, I get 2 hello_world folders and an email address that contains the word hello. In the launcher I just get the `help` app and with `d: hello` nothing pops up.
- [x] Continuation of autocompletion: When I type e.g. `~/Doc` I can use tab to complete to  `/home/jannik/Documents/`, but there is no more autocompletion popping up after the first completion.
- [ ] Starting to type in the workspaces view could automatically open up the launcher. Back with the gnome overview, I would often open the overview to see what is happening and then remember what application I want to launch. Right now there is no way do directly get to either the search or the launcher from the workspaces view.

Note: I originally opened a related issue in the pop/beta repo: https://github.com/pop-os/beta/issues/169. Pop-os is a blast to work with, keep up the good work! :)

### LINKED ISSUE #1087: Improve program name launcher sort order
This is a minor thing, but it would improve usability.

**(1) Issue/Bug Description:**
Launcher program search should prioritize matching first part of word.

**(2) Steps to reproduce (if you know):**
Install Steam and install the Microsoft Teams flatpak from Pop Shop. Bring up the launcher and type 'team'. Steam shows up before Microsoft Teams.
image

**(3) Expected behavior:**
Both of these should show up, but Microsoft Teams should show up first in the search. It is more likely that users will search for an app by typing one of the words in the name than typing out the middle part of one of the words.

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
3.38.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```pop-shell:
  Installed: 1.1.0~1626203716~21.04~021c931
  Candidate: 1.1.0~1626357201~21.04~c1f2ea4
  Version table:
     1.1.0~1626357201~21.04~c1f2ea4 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
 *** 1.1.0~1626203716~21.04~021c931 100
        100 /var/lib/dpkg/status
```

### LINKED ISSUE #1108: [FEATURE REQUEST] Currency Converter in launcher
Feature Request - An in built currency converter in launcher would add more usable functionality. We can still use the launcher to google the results. Just a thought that it would be awesome to have this inbuilt.

Please consider the possibility.

Cheers!

### LINKED ISSUE #1135: `20.04 lts` when I remove a '*.desktop' file in '~/.local/share/applications' and even in '/', it still could be found in Navigate through 'Super+/'
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I don't know its specific package name, Just use shortcuts 'Super+/' to open Navigate 

**Issue/Bug Description:**
for example, I manually install a binary file, '*.desktop' file in ~/.local/share/applications, and when I remove '*.desktop' file, in Gnome search, it will not exist, but When I use Navigate through 'Super+/', it still in there, I guess there exist some cache, but I don't know how to update it

**Steps to reproduce (if you know):**
1. create a '*.desktop' file in ~/.local/share/applications;
2. find it through 'Super+/';
3. rm desktop file in step 1;
4. it still could be found in 'Super+/';

**Expected behavior:**
1. it disappear in Navigate through shortcut: 'Super+/';

**Other Notes:**

### LINKED ISSUE #1141: Launcher doesn't calculate with "," instead of "." as decimal seperator
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Issue/Bug Description:**
When using the launcher to calculate something with the "=" prefix. It doesnt work with "," as decimal seperator. It works flawless with "."

**Steps to reproduce (if you know):**

1. Open launcher
2. Type "=1,1+1,1"

**Expected behavior:**
Output of 2,2.

**Other Notes:**
Region is set right and the examples in the settings are showing a "," as decimal seperator.

### PR DESCRIPTION
**Pull request by mmstick**
Requires package of https://github.com/pop-os/launcher to be installed

Removes a lot of JavaScript code. The UI code for the launcher remains, but all of the launcher filtering, sorting, and plugin management now exists in a separate Rust process. The launcher UI spawns the pop-launcher process and asynchronously listens to its responses while sending launcher events to it.

Some new DBus methods were added for the pop-shell plugin written for the launcher.

There is also fix for some window focusing issues. A window will now be activated through its workspace. It may be a GNOME 40 thing, but workspace shifting will not happen if you are activating a window directly. There is also a chance that a window being requested to activate does not actually have a clutter actor attached to it, so there's a check for that.

Closes #1141
Closes #1135
Closes #1108 
Closes #995
Closes #903 
Closes #849 
Closes #199
Closes #1087

### CODE REVIEW

**Comment by jacobgkau** [comment]
The Shell extension isn't starting after updating to this branch (and pulling in the `pop-launcher` dependency) on Hirsute:
```
Aug 13 14:00:25 pop-os gnome-shell[3293]: JS ERROR: Extension pop-shell@system76.com: Error: Schema org.gnome.shell.extensions.pop-shell could not be found for extension pop-shell@system76.com. Please check your installation
                                          getSettings@resource:///org/gnome/shell/misc/extensionUtils.js:151:15
                                          log_level@/usr/share/gnome-shell/extensions/pop-shell@system76.com/log.js:11:35
                                          info@/usr/share/gnome-shell/extensions/pop-shell@system76.com/log.js:27:9
                                          init@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:1914:9
                                          _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:435:50
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:27
                                          _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:597:18
                                          collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                          _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:572:19
                                          _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:606:18
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:637:18
                                          init@resource:///org/gnome/shell/ui/extensionSystem.js:57:14
                                          _initializeUI@resource:///org/gnome/shell/ui/main.js:272:22
                                          start@resource:///org/gnome/shell/ui/main.js:162:5
                                          @<main>:1:47
```

Also, it looks like https://github.com/pop-os/launcher failed to build on Focal:
```
cargo build -p pop-launcher-plugins --release --frozen --offline
error: failed to get `flume` as a dependency of package `pop-launcher-plugins v1.0.0 (/<<PKGBUILDDIR>>/plugins)`
Caused by:
  failed to load source for dependency `flume`
Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to parse manifest at `/<<PKGBUILDDIR>>/vendor/zvariant/Cargo.toml`
Caused by:
  feature `resolver` is required
  consider adding `cargo-features = ["resolver"]` to the manifest
```

**Comment by jacobgkau** [comment]
On a77b178, I am seeing the window list fail to load fairly often when only one window is open:

Screenshot from 2021-08-16 08-12-50

If I close and re-open the launcher a few times, then the single open window does sometimes show up in the list.

**Comment by jacobgkau** [comment]
Also, if I search and then clear the search text, the window list does not re-show.

**Comment by mmstick** [comment]
The latest version of pop-launcher has fixed the issue. The channel crate that I was using was sending messages out of order. Switched to a different crate which pops messages in the order they were pushed.

**Comment by mmstick** [comment]
Context option support (right click popup menu) has been reimplemented for desktop entries.

**Comment by jacobgkau** [comment]
The search results seem to hide and then re-show every time I add a character to the search, which results in flickering:

https://user-images.githubusercontent.com/7199422/129918338-9f9501cb-976a-4140-a3af-d276c204560a.mp4

Can we keep the old results on the screen until the new results are ready to display so this doesn't happen?

**Comment by jacobgkau** [comment]
When I first open the launcher, the first search result (which is selected by default) is a window, but the window is not highlighted like it should be:

Screenshot from 2021-08-18 12-20-53

If I move down and then back up in the results list, the window becomes highlighted:

Screenshot from 2021-08-18 12-20-56

**Comment by jacobgkau** [comment]
If I have a Settings page open, switch to a different workspace, then launch a different settings page through the Launcher, I get a `"Settings" is Ready` notification, but the workspace does not switch so I can see the Settings window like it used to.

**Comment by jacobgkau** [comment]
The search is not being cleared properly when I exit the launcher. For example, if I start with no windows open:

Screenshot from 2021-08-19 10-30-55

Perform a search:

Screenshot from 2021-08-19 10-34-11

Then exit the launcher with ESC, then open it again:

Screenshot from 2021-08-19 10-31-11

Now my search box is empty but I'm still seeing results from that search. Attempting to click on those results doesn't work, I need to enter something into the search box before the results are clickable/selectable. Also, the launcher opened up higher on the screen, which seems like an issue.

One other thing I noticed, the calculator search results now include a "by Qalc" message:

Screenshot from 2021-08-19 10-29-41

We didn't have a "by MathJS" message before, so I'm wondering if this is necessary to add. I'm not opposed to giving credit to other projects where it's due, but having it prominently in the UI like that might be a UX thing. (It looks like the actual name of the program/project is `Qalculate!`, and the command `qalc` is referred to either all-lowercase or all-caps in its man page, so the branding we're using also isn't super clear.)

**Comment by mmstick** [comment]
The description could be empty, but I figured that showing the name would indicate what you should search to find more information about it's specific math expression syntax.

**Comment by mmstick** [comment]
Contains fix that will close #1137

**Comment by jacobgkau** [comment]
> Contains fix that will close #1137

Is there a reason to include that here if it's included in https://github.com/pop-os/shell/pull/1148 anyway? It looks like the commit here contains an extra logging like that https://github.com/pop-os/shell/pull/1148 doesn't have, is that intended to be present or not?

**Comment by mmstick** [comment]
Rebased everything so that it's not required to be in the same PR.

**Comment by jacobgkau** [comment]
On 9960a8e, if no windows are open, then the search is not cleared if I type a character and then delete it. The results that are still shown are not clickable.

Screenshot from 2021-08-20 09-49-12

**Comment by jacobgkau** [comment]
Web searches don't seem to be working. Is that plugin going to be implemented in the new launcher? (Seems like we might want to keep out-of-the-box functionality that was previously available.)

**Comment by mmstick** [comment]
It will be working when the next version of launcher builds. The symlink for it was missing

**Comment by jacobgkau** [comment]
Web search is working now. However, the web search action seems to be interspersed with other search results (it used to be the only result when using a valid prefix):

Screenshot from 2021-08-23 10-04-02

Having other search results included isn't a problem, but the web search action should be the first item in the list. Without that constraint, we have some like the Pop!_Planet search where the search action doesn't show up because it's not high enough in the search results:

Screenshot from 2021-08-23 10-00-57

**Comment by mmstick** [comment]
The next version of the launcher will add support for prioritizing results from a plugin, and the web plugin will request a high priority so that it's search results always get bumped to the top.

**Comment by jacobgkau** [comment]
If I choose `Power Off`, `Restart`, or `Log Out`, the launcher does not close and the 60-second confirmation dialog shows up behind the launcher:

Screenshot from 2021-08-24 12-12-11

This is happening on both 21.04 and 20.04.

**Comment by mmstick** [comment]
I see. The standard output stream is getting closed before it signals to the launcher to close.

**Comment by mmstick** [comment]
Latest version of the launcher will have fixed that issue.

**Comment by jacobgkau** [comment]
It looks like pop-launcher failed to build on the build server:
```
The following warnings were emitted during compilation:
warning: Failed to run `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.48"`: No such file or directory (os error 2)
error: failed to run custom build command for `glib-sys v0.14.0`
Caused by:
  process didn't exit successfully: `/<<PKGBUILDDIR>>/target/release/build/glib-sys-de38c82711b78786/build-script-build` (exit code: 1)
  --- stdout
```

It also failed to build locally on a Hirsute machine, but with `cairo` in the error message instead of `glib-2.0`.

**Review by jacobgkau — APPROVED** [review]
Not seeing any more issues as compared to the current JS launcher. Regression testing has passed:
[shell-pr1139-hirsute.txt](https://github.com/pop-os/shell/files/7078043/shell-pr1139-hirsute.txt) - with pop-launcher version 5e2c38e.
[shell-pr1139-focal.txt](https://github.com/pop-os/shell/files/7078390/shell-pr1139-focal.txt) - with pop-launcher version 777fe78 (the only change between this version and 5e2c38e were comments and documentation files regarding licensing.)

Once this pop-shell PR is merged, future changes to pop-launcher will need to go through PRs instead of being pushed straight to master.

**Pull request merged**
