### PR TITLE
feat: Scrollable launcher results

### LINKED ISSUE #799: Launcher's Last Candidate Cut Off
**(1) Issue/Bug Description:**
image

When the max of 9 candidates are shown in the launcher the 9th candidate gets cut off. It is partially visible but I think it would be nice if it appeared fully.

**(2) Steps to reproduce (if you know):**
search the launcher for something with 9 or more candidates

**(3) Expected behavior:**
the candidates are all fully visible

**(4) Distribution (run `cat /etc/os-release`):**
Fedora 33 (Workstation Edition) 

**(5) Gnome Shell version:**
3.38.2

**(7) Where was Pop Shell installed from:**
master branch https://github.com/pop-os/shell/commit/c533b207d4d24ea56618d470927e120a42f7e379

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
16:9 (1366x768)

### PR DESCRIPTION
**Pull request by mmstick**
Closes #799

### CODE REVIEW

**Comment by jacobgkau** [comment]
Adds a scrollbar when launcher results would be cut off. Before:

Screenshot from 2021-01-05 11-16-22

After:

Screenshot from 2021-01-05 11-17-42

I did notice that the space for the scrollbar is reserved even when it isn't showing, which leads to off-center results when no scrollbar is present:

shell-pr808-offcenter

Is that something we want to address?

**Comment by mmstick** [comment]
Looking into if this is even possible

**Comment by mmstick** [comment]
Success. I found a way to hide it

**Review by jacobgkau — APPROVED** [review]
Scrollbar show/hide is working perfectly. No more regressions.

**Pull request merged**
