### PR TITLE
fix: Do not unstack last window with keyboard moves

### LINKED ISSUE #881: Last stacked window gets unstacked automatically
**(1) Issue/Bug Description:**
When I'm stacking two windows and I remove one of them from the stack, stacking mode is disabled. This started happening since commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941).

**(2) Steps to reproduce (if you know):**
- Make sure the shell has been updated recently (on or ahead of commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941))
- Stack two windows
- Remove one window from the stack
- Both windows will leave stacking mode

**(3) Expected behavior:**
- The window that was not moved should remain on stacking mode

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**(5) Gnome Shell version:**
```
$ apt policy gnome-shell:
  Installed: 3.36.4-1ubuntu1~20.04.2
  Candidate: 3.36.4-1ubuntu1~20.04.2
  Version table:
 *** 3.36.4-1ubuntu1~20.04.2 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.36.1-5ubuntu1 500
        500 http://br.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
commit 6b2287fa7ed61043d629325bd5ed17f74028418c (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Aaron Murphy <mmstick@pm.me>
Date:   Thu Feb 11 14:18:03 2021 -0700

    fix: Mouse dropping from stack to adjacent sibling

```

After a bit of investigation though, the bug only starts appearing on commit [0657c59](https://github.com/pop-os/shell/commit/0657c5908859f67ab688b7bab35eda0465e54941), which improved support for mouse tilling. Rolling back to its [parent](https://github.com/pop-os/shell/commit/190ad70fe9e7ebea928892443e3787f86d1dddb7) solved the bug!

**(7) Where was Pop Shell installed from:**
Built locally

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
None since it started happening

**(10) Other Notes:**
Thanks for developing Pop!_OS shell! It made GNOME orders of magnitude more powerful.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #881

### CODE REVIEW

**Comment by jacobgkau** [comment]
This doesn't just affect keyboard, it currently also prevents unstacking the last window when dragging with the mouse. After unstacking the second window with the mouse, trying to drag it back into the stack swaps instead.

**Comment by jacobgkau** [comment]
This doesn't just affect keyboard, it currently also prevents unstacking the last window when dragging with the mouse. Also, after unstacking the second window with the mouse, trying to drag it back into the stack swaps positions instead.

peek1

**Comment by jacobgkau** [comment]
@mmstick The behavior now seems to be reversed from what we want... the stack stays when dragging a window out with the mouse, but gets destroyed when removing a window with the keyboard.

peek3

**Comment by mmstick** [comment]
Flipping a bit

**Comment by jacobgkau** [comment]
Opened https://github.com/pop-os/shell/issues/889 for the issue I was seeing with swapping vs. stacking while dragging a window, since that's not a regression.

I also managed to create a ghost window:
Screenshot from 2021-02-23 16-37-41
Still looking into this one further, trying to figure out how to reproduce it so I can tell if it's a regression.

**Review by jacobgkau — APPROVED** [review]
Got the ghost window again. Confirmed it's not a regression. Opened an issue for it: https://github.com/pop-os/shell/issues/891 

I did observe that when full-screening an application in a stack and then quitting that app, the stack still gets destroyed if only one window is left. This PR is only supposed to affect keyboard movement, so that's fine.

Regression testing passed:
[shell-pr888-groovy.txt](https://github.com/pop-os/shell/files/6038560/shell-pr888-groovy.txt)
[shell-pr888-focal.txt](https://github.com/pop-os/shell/files/6038673/shell-pr888-focal.txt)

**Comment by mmstick** [comment]
Will certainly look into fixing the ghost tiling issue ASAP

**Pull request merged**
