### PR TITLE
fix: correctly hide the decoration on gnome 44 (#1622)

### LINKED ISSUE #1622: Title Bar doesn´t hide anymore on gnome 44
**(1) Issue/Bug Description:**
Title bar still visible with option show windows title off

**(2) Steps to reproduce (if you know):**
toggle off windows itle in extension settings

**(3) Expected behavior:**

hide titles in gtk apps 

**(4) Distribution (run `cat /etc/os-release`):**
 
archlinux

**(5) Gnome Shell version:**

44.1

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1080p

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

image

### PR DESCRIPTION
**Pull request by kneirinck**
This PR fixes #1622 and is based on the suggestion https://github.com/velitasali/gtktitlebar/issues/36#issuecomment-1455278899

### CODE REVIEW

**Review by mmstick — CHANGES_REQUESTED** [review]
This should be version checked to apply this behavior only for GNOME 44+

**Review by jacobgkau — CHANGES_REQUESTED** [review]
This indeed causes an issue on Pop!_OS 22.04 (with GNOME 42): window titles still hide when turned off, but when turning them back on, they're not shown again until windows are closed and re-opened.

**Comment by kneirinck** [comment]
> This indeed causes an issue on Pop!_OS 22.04 (with GNOME 42): window titles still hide when turned off, but when turning them back on, they're not shown again until windows are closed and re-opened.

Hmm crap indeed, not working as intended on that part.
It seems the `may_decorate` function is broken because of this change.
It checks if the 3rd motif hint is different from `0x0` but with my change it is set to `0x0` to hide the title bar.
Not really sure how I can safely check now to make `may_decorate` behave as before.
Suggestions are welcomed :)

**Comment by jacobgkau** [comment]
>  Suggestions are welcomed :)

Michael's suggestion was to version check GNOME to only apply the change on 44+, to start. If this is an improvement overall on 44+, then we could still consider it if it doesn't break earlier versions.

**Comment by akumaburn** [comment]
This does correctly hide on gnome 44 but it won't correctly show for me, looks like the show window title hint is still incorrect.

**Comment by ghostdevv** [comment]
Hey @kneirinck did you get another chance to look at this?

**Comment by ghostdevv** [comment]
This is fixed by #1661

**Comment by jacobgkau** [comment]
I'll go ahead and close this one, then. Thank you both for the contributions.

**Pull request closed without merging**
