### PR TITLE
Exceptions

### LINKED ISSUE #1104: Tilix in quake mode is being tiled like other windows
**(1) Issue/Bug Description:**

Since I updated to the last version of Pop-shell (I don't do regular update so I don't know in which version it was introduce, sorry) Tilix in quake mode is being tiled like other windows, before tilix normal windows where tiled but not the quake ones.

While searching if the issue was already know I found this one that look like it but for an other application : #1034 but in the case I can't just add it to the exception because I can't differentiate the quake windows from the normal ones.

**(2) Steps to reproduce (if you know):**

1. Install tilix from apt repository
2. Enable tiling in pop-shell
3. Start Tilix in quake mode `tilix -q`

**(3) Expected behavior:**

Tilix should be shown above other windows from the top of the screen, like the classic quake-terminal.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

3.36.8

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installé : 1.1.0~1626728027~20.04~9616931
  Candidat : 1.1.0~1626728027~20.04~9616931
 Table de version :
 *** 1.1.0~1626728027~20.04~9616931 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Bundled with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

From left to right (all are horizontal) : 

* 1920x1080  @ 100%
* 3840x2160 @ 150%
* 1920x1200 @ 100%

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

N/A

### LINKED ISSUE #1149: Add krunner to floating window exceptions
1. Install kde according to instructions
2. Use Pop as desktop
3. Use floating windows
4. Launch `krunner`

### LINKED ISSUE #1170: [Floating window exception request] Steam login and Steam guard
Steam login and steam guard windows should be added to the floating window system exception list.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #1104 
Closes #1170 
Closes #1149

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The Steam login window is still being tiled. Any idea why?

**Comment by mmstick** [comment]
Will verify correct regex for this

**Comment by mmstick** [comment]
My "Steam Login" window is floating, but the loading window is not.

**Comment by jacobgkau** [comment]
On 8789cc7, the login window itself is being tiled, but the preceeding Login/Create Account window is not:

https://user-images.githubusercontent.com/7199422/133102995-a1825af2-60a1-453c-8e63-585ca5605157.mp4

It seems the first window just uses a class and title of `Steam`, so there may not be an easy way to identify it, unless looking for a size of 432x438 in the same way as the <400x<200 check is an option.

**Review by jackpot51 — DISMISSED** [review]

**Review by jacobgkau — APPROVED** [review]
The first-time login/create account window is now floating along with the rest of the login flow. The main Steam window still tiles normally (and it can't be shrunk enough to cause these new rules to apply.)

Confirmed this fixes https://github.com/pop-os/shell/issues/1104, https://github.com/pop-os/shell/issues/1170, and https://github.com/pop-os/shell/issues/1149.

Regression testing passed on Hirsute and Focal:
[shell-pr1172-hirsute.txt](https://github.com/pop-os/shell/files/7156187/shell-pr1172-hirsute.txt)
[shell-pr1172-focal.txt](https://github.com/pop-os/shell/files/7156358/shell-pr1172-focal.txt)

**Pull request merged**
