### PR TITLE
Feature: Add option to disable moving mouse cursor on keyboard navigation

### LINKED ISSUE #1188: move_pointer_on_switch=false doesn't work
**(1) Issue/Bug Description:**
- `"move_pointer_on_switch": false` in `config.json` has no effect

**(2) Steps to reproduce (if you know):**
- Open `config.json`, set `move_pointer_on_switch` to `false
- Open two windows
- Switch between the two windows and note that the pointer _does_ move

**(3) Expected behavior:**
- The pointer stays where it was last moved _manually_ with the mouse

**(4) Distribution (run `cat /etc/os-release`):**
```
$ cat /etc/os-release
NAME=Fedora
VERSION="34 (Thirty Four)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Thirty Four)"
```

**(5) Gnome Shell version:**
- `40.4.0` running `X`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
- Not 100% sure how to obtain this when built from source (code is cloned into a `mktemp` directory and removed later).

**(7) Where was Pop Shell installed from:**
- Built from source

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
- Single, `3840x1600`

**(9) Other Installed/Enabled Extensions:**
image

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by AKK9**
This is my attempt at implementing #1188.

Do I need to add a new scenario to TESTING.md?

Does the setting summary `Move cursor to active window when switching via keyboard shortcuts` accurately describe the behaviour here?

Also looking for suggestions on the label for this setting in the settings window, it doesn't make much sense at the moment.

### CODE REVIEW

**Review by mmstick — DISMISSED** [review]

**Comment by jacobgkau** [comment]
Thank you for implementing this. It seems to be working as I'd expect.

> Does the setting summary `Move cursor to active window when switching via keyboard shortcuts` accurately describe the behaviour here?
> 
> Also looking for suggestions on the label for this setting in the settings window, it doesn't make much sense at the moment.

The GUI currently says `Move Mouse Cursor when Switching`. The word "switching" is a little ambiguous-- it's referring to both navigating windows and switching workspaces. For the longer description, `via keyboard shortcuts` doesn't cover everything since it also takes effect for touchpad gestures (4-finger workspace switching and 3-finger window navigation). I would propose the following:

- `Mouse Cursor Follows Active Window` for the GUI option.
- `Move cursor to active window when navigating with keyboard shortcuts or touchpad gestures` for the longer description.

I also wanted to point out that we still have a hidden option in the `~/.config/pop-shell/config.json` text config called `move_pointer_on_switch`, and the similarity between this new feature and that one could be confusing. That existing option, added in https://github.com/pop-os/shell/pull/646, was specifically for switching between applications using Super+Tab and windows using Alt+Tab (not for Super+Arrow-key navigation).

`move_pointer_on_switch` doesn't seem to work anymore. It's not a regression from this change, it's just not working on 22.04 or 20.04 right now-- the cursor doesn't move to the active window when switching with Alt+Tab or Super+Tab on the same workspace, even if that option is set to `true`. On 22.04 (but not 20.04), the mouse cursor does follow the active window when switching between workspaces with Alt+Tab or Super+Tab if this new option is enabled, regardless of what the old option is set to. We'll probably want to get rid of `move_pointer_on_switch`, and make Alt+Tab/Super+Tab on the same workspace follow the new option consistently with everything else. (That doesn't necessarily need to happen in this PR.)

**Comment by AKK9** [comment]
@jacobgkau Thanks for the suggestion and the extra context. I've updated the naming based on your suggestions and updated the variable/function names too for consistency.

It seems that functionality was removed as part of this commit:
https://github.com/pop-os/shell/commit/b68a38c12af9bcd7cf41d4e1110b1547f2e59c5e

As a result it looks like that config item is not longer used. Want me to remove `move_pointer_on_switch` from `config.ts`?

Yeah I think it's best to keep the Alt + Tab part out of this PR. I don't have the knowledge to tackle this.

**Comment by AKK9** [comment]
On a second look, maybe we could amend the `_finish()` functions on the `AppSwitcherPopup`, `WindowSwitcherPopup` and `CyclerPopup` classes in `imports.ui.altTab`?
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/altTab.js#L271

They could perform their original function, then we could set the mouse pointer position? But modifying prototype is probably not a good idea. Given my lack of knowledge here maybe this is best for a separate PR.

**Comment by jacobgkau** [comment]
> It seems that functionality was removed as part of this commit: [b68a38c](https://github.com/pop-os/shell/commit/b68a38c12af9bcd7cf41d4e1110b1547f2e59c5e)
> 
> As a result it looks like that config item is not longer used. Want me to remove `move_pointer_on_switch` from `config.ts`?

I see. Yes, if that config item is not being used anywhere (and I don't see anywhere it's being used), let's remove it so nobody sees it and thinks it's related to what's being added now. (I expect it might stay in the config file on existing installations where the file's already been created, but no reason to keep creating it for new installations if it doesn't do anything.)

We don't have to worry about getting Super+Tab/Meta+Tab pointer movement working right now, the feature the PR is adding is off by default and only part of the advanced settings, and will be useful enough as it is.

**Review by jacobgkau — APPROVED** [review]
Regression testing passed, tested with default settings and with the new option enabled:
[shell-pr1417-jammy.txt](https://github.com/pop-os/shell/files/8642204/shell-pr1417-jammy.txt)
[shell-pr1417-jammy-nopointermovement.txt](https://github.com/pop-os/shell/files/8642328/shell-pr1417-jammy-nopointermovement.txt)

Having some problems with focus being lost when moving windows between workspaces, but that is not a regression:
- https://github.com/pop-os/shell/issues/1415 
- https://github.com/pop-os/shell/issues/1421

**Review by mmstick — APPROVED** [review]

**Pull request merged**
