### PR TITLE
feat: Make Pop Shell features accessible from the launcher

### LINKED ISSUE #817: Keyboard shortcut to toggle window titles
**(1) Issue/Bug Description:**
Use a shortcut key to toggle window titles.

Would be nice to have a shortcut key assigned to toggle windows titles. Some applications don't honor hiding the title so I normally have to toggle the window title to hide the window title.

**(3) Expected behavior:**
Use a shortcut key to toggle window titles

**(4) Distribution (run `cat /etc/os-release`):**
 ```
❯ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```3.38.1```

**(6) Pop Shell version 
```
❯ apt policy pop-shell
pop-shell:
  Installed: 1.1.0~1609890630~20.10~3b05ab5
  Candidate: 1.1.0~1609890630~20.10~3b05ab5
  Version table:
 *** 1.1.0~1609890630~20.10~3b05ab5 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

### LINKED ISSUE #827: Add Suspend to the launcher
Appears that all other session management is present except suspend.

```
apt-cache policy pop-shell
pop-shell:
  Installed: 1.1.0~1610483356~20.10~891525b
  Candidate: 1.1.0~1610483356~20.10~891525b
  ```

### PR DESCRIPTION
**Pull request by mmstick**
Adds the following options to the launcher:

- Toggle Active Hint
- Toggle Orientation
- Toggle Stacking
- Toggle Window Titles
- Toggle Window Tiling

Closes #827 
Closes #817

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Some of the entries are currently mixed up:

- `Toggle Active Hint` toggles stacking.
- `Toggle Stacking` toggles window titles.
- `Toggle Window Titles` toggles the active hint.
- `Toggle Orientation` is working as expected.

https://www.dropbox.com/s/ytevzc6mpgt9a70/shell-pr826-screencast2.mkv?dl=0

**Comment by jacobgkau** [comment]
The cases in [this section](https://github.com/pop-os/shell/blob/01c9c0dbe9507a102997714ecf79339835afa491/src/plugin_shell.ts#L10) don't match up with the cases in [this section](https://github.com/pop-os/shell/blob/01c9c0dbe9507a102997714ecf79339835afa491/src/plugin_shell.ts#L45), that looks like the problem.

**Comment by mmstick** [comment]
Fixed

**Comment by jacobgkau** [comment]
All four toggles are now working. I've got the top-right menu `Show Window Titles` toggle not matching up with the actual state of that feature:

shell-pr826-screenshot1

(The on/off switch is on, but Evolution is not showing a window title.) It seems the on/off switch is just not updating when I use the Launcher toggle.

**Comment by mmstick** [comment]
I think there was an open issue for the statuses being reported here not being in line with actual settings sometimes. I'll have them recheck status on opening the menu

**Review by jacobgkau — APPROVED** [review]
All of the new additions are working, no regressions.
[shell-pr826-groovy.txt](https://github.com/pop-os/shell/files/5816427/shell-pr826-groovy.txt)
[shell-pr826-focal.txt](https://github.com/pop-os/shell/files/5816467/shell-pr826-focal.txt)

Small UX note regarding the toggle to enable/disable tiling: the top-right menu labels that option `Tile Windows`, but searching for `tile` in the launcher doesn't return that item as a result since it's called `Toggle Window Tiling` in the launcher. The launcher item matches up with the rest of the toggles, so not necessarily an issue, but maybe something to consider.

**Pull request merged**
