### PR TITLE
Shell Improvements

### LINKED ISSUE #1345: Can't minimize if only one window is open
**(1) Issue/Bug Description:**

Can't hide / minimize when only one window is active

**(2) Steps to reproduce (if you know):**

Minimize all windows but one

**(3) Expected behavior:**

In the past i was able to hide all windows and see the desktop

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

41.3

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Not sure, package is 1.2.0^5.21745c4-1.fc35

**(7) Where was Pop Shell installed from:**

Fedora repository

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 3440x1440

**(9) Other Installed/Enabled Extensions:**

**(10) Other Notes:**

### LINKED ISSUE #1436: moving to workspace with only minimized windows will maximize one of them
**(1) Issue/Bug Description:**

Having workspace with only minimized windows if you move to this workspace with the extension enabled it will maximize one of them.

**(2) Steps to reproduce (if you know):**

1. Create new workspace 
2. Open application X on it
3. Minimize application X on it
4. Move to another workspace and back to the workspace with application X
5. Observe application X being maximised and focused

**(3) Expected behavior:**

Application X does not get maximized. 

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

Gnome 42? Not sure where to get this information from.

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

**(7) Where was Pop Shell installed from:**

Come in with pop os

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

```
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 16384 x 16384
eDP-1 connected 1920x1080+2560+360 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-1-8 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   2048x1080     60.00    24.00  
   1920x1080     60.00    50.00    59.94  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP-1-1 disconnected (normal left inverted right x axis y axis)
```

**(9) Other Installed/Enabled Extensions:**

image

**(10) Other Notes:**

### LINKED ISSUE #1438: GNOME "Edge Tiling" remains active when using the Pop Shell's tiling mode
**Distribution (run `cat /etc/os-release`):** `Pop!_OS 22.04 LTS`
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-shell:
  Installed: 1.1.0~1652463555~22.04~034fb14
  Candidate: 1.1.0~1652463555~22.04~034fb14
  Version table:
 *** 1.1.0~1652463555~22.04~034fb14 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:** When the tiling mode of Pop Shell is enabled, it is still possible to use GNOME's "Edge Tiling" feature (also known as windows snapping) which resizes windows to full screen when dragged to the top of the screen, and to half screen when dragged to a side edge. However, if "Edge Tiling" is used (which can happen accidentally when dragging windows with mouse), the tiling manager gets confused and starts ignoring the snapped window.

**Steps to reproduce (if you know):** Enable tiling mode in Pop Shell, open several windows, drag one to a screen edge and observe the behavior

**Expected behavior:** "Edge Tiling" should be disabled when the tiling mode is active, as the behavior is conflicting and redundant.

**Other Notes:** For the time being, "Edge Tiling" can be disabled by:

```
gsettings set org.gnome.mutter edge-tiling false
```

There is a related issue, pop-os/gnome-control-center#231, which asks for a toggle to completely disable this feature regardless of tiling mode. If this gets implemented, I believe that the correct course of action would be to always disable "Edge Tiling" in the Pop Shell's tiling mode regardless of the toggle position, as there is no conceivable use for it in this mode.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #1436 
Closes #1438 
Closes #1345

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
This fixes https://github.com/pop-os/shell/issues/1345 and allows minimizing a single window in tiling mode. However, the active hint sometimes comes back just after the window is minimized:

Screenshot from 2022-05-17 14-58-15

**Comment by mmstick** [comment]
That should be fixed now. Active hint conditions are now checked when it's set a second time (a workaround for active hint not appearing on workspace switch).

**Comment by n3m0-22** [comment]
This seems to have fixed all the issues including the active hint coming back.

**Comment by jacobgkau** [comment]
I am still seeing the active hint not show up if I drag a non-active tiled window to another workspace, float it, then switch it back to the first workspace:

https://user-images.githubusercontent.com/7199422/169096219-ee740895-5fa6-465b-8ba7-9608068db7d6.mp4

However, this doesn't seem to be a regression from master, so I'm continuing with testing.

**Review by jacobgkau — APPROVED** [review]
Confirmed the following issues are fixed:
- [X] https://github.com/pop-os/shell/issues/1436
- [X] https://github.com/pop-os/shell/issues/1438
- [X] https://github.com/pop-os/shell/issues/1345

Regression testing passed: [shell-pr1429-jammy.txt](https://github.com/pop-os/shell/files/8718424/shell-pr1429-jammy.txt)

**Comment by n3m0-22** [comment]
GNOME's "Edge Tiling" still partially works when tilting mode is enabled, but the window goes back to tiling mode when another window is selected.

Steps to reproduce:

1. with tiling mode on open two windows on a workspace
2. `super` + `ctrl` + `arrow` to either side
3. select other window

This will also work for a single windows on a workspace but will go back to normal by opening another window, minimizing the window and bringing back up or `super` + `M` twice.

**Comment by jacobgkau** [comment]
The Mutter option to control edge tiling only affects dragging to the edge of the display with the mouse. The keyboard shortcuts for those items are `View split on left` and `View split on right`. The behavior for the keyboard shortcuts is in line with current pop-shell, and the mouse is mainly what conflicts with pop-shell's interface.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
