### PR TITLE
feat: Add support for GNOME 40

### LINKED ISSUE #908: Pop Shell 1.2.0 is incompatible with GNOME 40
**(1) Issue/Bug Description:**
I suppose this is less urgent of an issue for Pop!_OS. I'm testing the upcoming GNOME 40 (currently in beta) in a virtual machine of Rawhide (development branch of Fedora) x86_64. I'm using the RPM build of Pop Shell extension v1.2.0.

Looking Glass shows no error messages for Pop Shell (because the extension hasn't been enabled yet). But in the GNOME Extensions app, there's a red ⛔ warning icon next to Pop Shell, and the toggle switch to enable it is grayed out. If you click the gear icon to see Pop Shell settings, you get a dialog that says "Something went wrong" and the following error message:

```
Error: No property border_width on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  settings_dialog_view@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:46:16
  settings_dialog_new@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:9:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/pop-shell@system76.com/prefs.js:127:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

```

In case you haven't seen it yet, the new GNOME versioning scheme was discussed and [announced on their Discourse](https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235) and probably elsewhere, and a recent blog post [goes over some of the API changes relevant to Shell extensions](https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/).

**(2) Steps to reproduce (if you know):**

1. Install GNOME 40.beta, perhaps in a VM.
2. Install Pop Shell.
3. Log out of the GNOME session, log in again.
4. Launch GNOME Extensions and attempt to enable Pop Shell.

**(3) Expected behavior:**
It'd be great to be able to try out Pop Shell on Fedora 34 when it comes out of beta, but for now it won't load.

**(4) Distribution (run `cat /etc/os-release`):**
 ```
NAME=Fedora
VERSION="35 (Workstation Edition Prerelease)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora 35 (Workstation Edition Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:** 40.beta

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
  ↪ sudo dnf info gnome-shell-extension-pop-shell
[sudo] password for audrey: 
Last metadata expiration check: 2:05:36 ago on Mon 15 Mar 2021 02:44:42 PM PDT.
Installed Packages
Name         : gnome-shell-extension-pop-shell
Version      : 1.2.0
Release      : 3.fc35
Architecture : noarch
Size         : 1.0 M
Source       : gnome-shell-extension-pop-shell-1.2.0-3.fc35.src.rpm
Repository   : @System
From repo    : rawhide
Summary      : GNOME Shell extension for advanced tiling window management
URL          : https://github.com/pop-os/shell
License      : GPLv3 and ASL 2.0 and MIT
Description  : Pop Shell is a keyboard-driven layer for GNOME Shell which allows for quick and
             : sensible navigation and management of windows.  The core feature of Pop Shell
             : is the addition of advanced tiling window management - a feature that has been
             : highly-sought within our community.  For many - ourselves included - i3wm has
             : become the leading competitor to the GNOME desktop.
```

**(7) Where was Pop Shell installed from:**
Fedora package repositories.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
VM window sized at 1920×1080 (within a physical 4K monitor).

**(9) Other Installed/Enabled Extensions:**
None.

### PR DESCRIPTION
**Pull request by scaryrawr**
Fixes #908

### CODE REVIEW

**Review by azatserikbaev — APPROVED** [review]
Extension works on gnome 40, but Overview breaks because of native-window-placement extension, which is enabled by `scripts/configure.sh. It can be fixed by manually disabling this extension, unless its behavior fixed in upstream

**Review by jacobgkau — APPROVED** [review]
Should the metadata list 3.38 as a supported shell version in addition to 3.36 and 40.beta? We've been supporting 3.38 for some time since it's what 20.10 includes.

Aside from that (which isn't a regression), I don't see any problems with these changes. Regression testing passed on Groovy (3.38) and Focal (3.36).
[shell-pr909-groovy.txt](https://github.com/pop-os/shell/files/6150553/shell-pr909-groovy.txt)
[shell-pr909-focal.txt](https://github.com/pop-os/shell/files/6150776/shell-pr909-focal.txt)

Also confirmed the extension works on GNOME 40/Fedora 34 Beta with these changes. It does seem that resizing with the mouse is broken in GNOME 40; I can only resize windows with the keyboard while tiling is enabled. (Resizing with the mouse works fine when tiling is disabled.) Still an improvement over not being able to enable the extension at all.

**Comment by mmstick** [comment]
I can add 3.38, but this list is useless to us right now since we're not publishing to the extensions site.

**Comment by audreytoskin** [comment]
GNOME Shell itself does check extensions' declared supported Shell versions in metadata.json -- at least as of GNOME 40. So, maybe not entirely useless.

**Comment by elshize** [comment]
FYI, I tested the master version of the extension today on a fresh vm with fedora 34 beta (running gnome 40 beta) and it only partially works. It seems to do tiling correctly but doesn't do any resizing. I can move windows and all, just the resizing part seems to be broken:
popshell

Granted, this is a pre-release but I thought I'd let you guys know.

**Comment by scaryrawr** [comment]
> FYI, I tested the master version of the extension today on a fresh vm with fedora 34 beta (running gnome 40 beta) and it only partially works. It seems to do tiling correctly but doesn't do any resizing. I can move windows and all, just the resizing part seems to be broken:
> popshell
> 
> Granted, this is a pre-release but I thought I'd let you guys know.

Thanks @elshize ! Can you create a new issue with the information? Other folks might have an idea on what's changed in GNOME-40 that would break the window resizing and might not see the comment on the PR here.

**Comment by elshize** [comment]
@scaryrawr Sure, will do.

**Comment by elshize** [comment]
@scaryrawr I added #912 but one piece of update: I didn't realize that by default Fedora ran GNOME on Wayland. I checked on X and tiling looks okay, so it seems to be a problem only on Wayland (which I have mentioned in the new issue).

**Comment by rbutoi** [comment]
Will this work if I try replacing "40.beta" with "40"? (can report back later with results)

**Pull request merged**
