### PR TITLE
feat(tiling): Recheck tiling exceptions on window title change

### PR DESCRIPTION
**Pull request by mmstick**
Fixes exceptions for windows that change their titles dynamically after initialization

### CODE REVIEW

**Comment by jacobgkau** [comment]
If I understand correctly, this should fix #778. However, I'm getting inconsistent behavior with it:

- With Nautilus, the exception is not applied at window open, but is applied after the title is changed to something else and then back to what I've excepted. https://www.dropbox.com/s/qrwy13b51vjavn2/shell-pr795-screencast1.mkv?dl=0 
- With Termianl, the exception is sometimes applied at window open and sometimes not. When it's not applied, window management mode seems to treat it as if it's floating, then the shell re-tiles it after I try to move it. This would probably mean a fail for regression testing, since I'm unable to move/resize the window in window management mode. https://www.dropbox.com/s/p1wd242u673mo8h/shell-pr795-screencast2.mkv?dl=0

**Comment by mmstick** [comment]
The problem with Terminal and Nautilus is that the title changes whenever you switch a directory, so window-specific tiling doesn't work very well with it.

**Comment by jacobgkau** [comment]
I agree title-specific floating exceptions with those apps would be impractical. I'm more concerned about the inconsistent behavior after the changes.

**Comment by mmstick** [comment]
Yeah, this does break more than it fixes, so I'm closing

**Pull request closed without merging**
