### PR TITLE
fix: Phantom apps in dash after closing the last window in a workspace

### PR DESCRIPTION
**Pull request by mmstick**
Possibly addresses #220

### CODE REVIEW

**Comment by brs17** [comment]
## With tiling enabled

### Tiling

- [x] Super direction keys changes focus in the correct direction
- [x] Windows moved with the keyboard tile into place
- [x] Windows moved with the mouse tile into place
- [x] Windows swap with the keyboard (test with different size windows)
- [x] Windows can be resized with the keyboard (Test resizing four windows above, below, right, and left to ensure shortcut consistency)
- [x] Windows can be resized with the mouse
- [x] Minimizing a window detaches it from the tree and re-tiles remaining windows
- [ ] Unminimizing a window re-tiles it into its previous location
- [x] Maximizing removes the active hint and covers tiled windows
- [x] Umaximizing adds active hint and re-tiles into place
- [x] Full-screening removes the hint and full-screens on one display 
- [x] Unfull-screening adds active hint and re-tiles into place
- [x] Maximizing a YouTube video fills the screen and unmaximizing retiles the browser in place
- [x] VIM shortcuts work as direction keys
- [x] `Super` `O` changes window orientation
- [?] `Super` `G` floats and then re-tiles a window
- [x] Float a window with `Super` `G`. It should be movable and resizeable in window management mode with keyboard keys
- [x] `Super` `Q` Closes a window
- [x] `Super` `M` Maximizes and un-maximizes a window
- [x] Turn off auto-tiling. New windows launch floating.
- [x] Turn on auto-tiling. Windows automatically tile.
- [x] Disabling and enabling auto-tiling correctly handles minimized, maximized, fullscreen, floating, and non-floating windows (This test needs a better definition, steps, or to be separated out.)

### Workspaces

- [x] Windows can be moved to another workspace with the keyboard
- [x] Windows can be moved to another workspace with the mouse
- [x] Windows can be moved to workspaces between existing workspaces
  - Works except when moving to a new workspace at the very beginning of the stack. 
- [x] Moving windows to another workspace re-tiled the previous and new workspace
- [x] Active hint is present on the new workspace and once the window is returned to its previous workspace
- [x] Floating windows move across workspaces
- [x] Remove windows from the 2nd workspace in a 3 workspace setup. The 3rd workspace becomes the 2nd workspace, and tiling is unaffected by the move.

### Displays

- [x] Windows move across displays in adjustment mode with direction keys
- [x] Windows move across displays with the mouse
- [x] Changing the primary display moves the top bar. Window heights adjust on all monitors for the new position.
- [x] Unplug a display - windows from the display retile on a new workspace on the remaining display
- [ ] Plug in a display - windows and workspaces don't change
  - WINDOWS MOVE TO NEW MONITOR
- [ ] NOTE: Add vertical monitor layout test

### Launcher

- [x] All windows on all workspaces appear on launch
- [x] Choosing an app on another workspace moves workspaces and focus to that app
- [x] Launching an application works
- [x] Typing text and then removing it will re-show those windows
- [x] Search works for applications and windows
- [x] Search works for GNOME settings panels
- [x] Search for "Extensions". There should be only one entry.
- [x] The overlay hint correctly highlights the selected window
- [x] t: executes a command in a terminal
- [x] : executes a command in sh
- [x] = calculates an equation

### Window Titles

- [x] Disabling window titles in Firefox works (Check debian and flatpak packages)

## With Tiling Disabled

### Tiling

- [x] Super direction keys changes focus in the correct direction
- [x] Windows can be moved with the keyboard
- [x] Windows can be moved with the mouse
- [x] Windows swap with the keyboard (test with different size windows)
- [x] Windows can be resized with the keyboard (Test resizing four windows above, below, right, and left to ensure shortcut consistency)
- [x] Windows can be resized with the mouse
- [x] Windows can be half-tiled left and right with `Ctrl``Super``left`/`right`

### Displays

- [x] Windows move across displays in adjustment mode with directions keys
- [x] Windows move across displays with the mouse

**Comment by mmstick** [comment]
@brs17 This fixes the ones that appear when closing the last window on a workspace. There may yet to be other areas causing this, but these have been happening before the dev branch was merged. I do have a possible idea of a workaround for those, however.

**Comment by mmstick** [comment]
@brs17 I've added a new commit which attempts to handle other possible cases as well

**Comment by mmstick** [comment]
Nevermind that last commit. Causes a lot of issues

**Comment by mmstick** [comment]
I'll follow with more fixes to this in the dev branch

**Pull request merged**
