### PR TITLE
Fix skip taskbar

### LINKED ISSUE #1022: Sleek app does not show up in any Window management tools when "Minimize to tray" option is enabled.
**(1) Issue/Bug Description:**

When "Minimize to tray bar" is enabled the Sleek application (installed via flatpak) no longer appears in any Window management tool. (Super+tab,Launcher,Workspace Preview,Spread,Dash) 

**(2) Steps to reproduce (if you know):**

Install Sleek via flatpak install or Pop!_Shop
Enable "Minimize to tray bar" in settings.

**(3) Expected behavior:**

Sleek window should appear in the window management tools regardless to whether this option is set.

**(4) Distribution (run `cat /etc/os-release`):**
 
Tested and confirmed on 20.04, 20.10, and 21.04

**(5) Gnome Shell version:**

Latest tested: `3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Latest tested:  `1.1.0~1624408005~21.04~43a4386`

**(7) Where was Pop Shell installed from:**

Standard distribution

**(8) Other Installed/Enabled Extensions:**

Default extensions installed by the OS

**(9) Other Notes:**

Issue only appears with the aforementioned option is enabled, otherwise the application works as expected. Video, showing the issue. 

https://user-images.githubusercontent.com/10382037/123155969-f8eb9800-d425-11eb-84e3-b80e72ae148c.mp4

Note PR https://github.com/pop-os/shell/pull/1021 has been applied which fixes the window placement issue noted in https://github.com/pop-os/shell/issues/1009

### LINKED ISSUE #1023: Sleek application cannot be focused,and is ignored using keyboard controls when "Minimize to tray bar" enabled
**(1) Issue/Bug Description:**
When using Sleek (flatpak) with "Minimize to tray bar" enabled and with the keyboard control fix applied (https://github.com/pop-os/shell/pull/1021) you can control the Sleek window as long as it has focus. Moving focus to another app is possible but not the reverse. The issue also appears to affect the ability to move other windows in relation to Sleek. 

**(2) Steps to reproduce (if you know):**
(Assuming above fix is applied) 
Install Sleek via flatpak or Pop!_Shop
Enable "Minimize to tray bar" in Sleek
Add a Sleek window and one other window (not Sleek)

With tiling and active hint enabled:
  * Select Sleek via mouse and move it right or left. (should work)
  * Use keyboard to change focus to non Sleek window (should work)
  * Use keyboard to change focus to Sleek. (doesn't work)
  * Use keyboard to move non Sleek window left or right (doesn't work)

Having multiple monitors show similar results. 

**(3) Expected behavior:**

Sleek should behave the same whether or not "Minimize to tray bar" is enabled.

**(4) Distribution (run `cat /etc/os-release`):**

 Issue appears on 20.04,20.10,21.04

**(5) Gnome Shell version:**

Latest tested: `3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d`

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

Latest tested:  `1.1.0~1624408005~21.04~43a4386`

**(7) Where was Pop Shell installed from:**

Standard Distribution

**(8) Other Installed/Enabled Extensions:**

Default extensions installed by the OS

### PR DESCRIPTION
**Pull request by jmmaranan**
Fixes #1022 workspace thumbnail, overview, launcher, switch-apps, switch-windows
Fixes #1023 - add keyboard control

### CODE REVIEW

**Comment by jmmaranan** [comment]
The dash is harder to override on _init. Will skip on this PR.

**Comment by mmstick** [comment]
Needs to be rebased on master as one commit

**Comment by jmmaranan** [comment]
Done rebasing into a single commit

**Comment by jacobgkau** [comment]
I'm seeing this fix #1022, but not #1023-- with minimize-to-tray enabled, the Sleek app now shows up in the Workspaces overview, but I still can't navigate to it via Super + arrow keys (and it can get stuck on the side of a screen where I can't move other windows around it.)

https://user-images.githubusercontent.com/7199422/123997167-52574800-d98d-11eb-8d8d-e6804e8694b3.mp4

We can move forward with the #1022 fix if you remove #1023 from the PR description, or we can wait for the #1023 fix to be completed/fixed.

**Comment by jmmaranan** [comment]
Will check 🤔

**Comment by jmmaranan** [comment]
@jacobgkau - missed something on the rebase down to one commit. shortcut nav should work now

**Comment by jmmaranan** [comment]
I just want to point out one item on #1022. 

The integrated dock for skip taskbars to appear on these types of windows can be fixed I think here:
https://github.com/pop-os/cosmic-dock/blob/5cfe4323afef7c08c9a2df78ce9e64274760e2e6/appIcons.js#L1065 

But for non-dock users, a little bit harder since looks like re-implementing a small portion of dash.js just to override the _redisplay()

**Pull request merged**
