### PR TITLE
fix: Smart gap appearing on workspace with only stacked windows

### LINKED ISSUE #588: Smart Gap is removed on a work area with two windows in a stack
**(1) Issue/Bug Description:**
Smart gaps and stacking and awesome features, thank you guys for adding them.
One odd behaviour i found with using both is that stacking doesn't always respect smart gaps.
e.g. if i open a terminal, set it to stacking - there are no gaps. as soon as i add another terminal, gaps are added. but if i add one more terminal (so have 3 at a time), and close it - the gaps are gone.
So it seems like opening a window in the stack triggers the gaps to be added, and removing one triggers the smart gap logic, and the gaps are gone.

**(2) Steps to reproduce (if you know):**
1. With smart gaps enabled, open up a window, set it to stacking mode - there are no gaps
2. Open another window in the stack - observe the gaps
3. Open a third window - gaps still present
4. Close the third window - gaps are gone

**(3) Expected behavior:**
One stack on screen, with smart gaps on, should always have no gaps around the stack.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
```
[~] apt policy gnome-shell                                                                              
gnome-shell:
  Installed: 3.36.4-1ubuntu1~20.04.2pop1~1597874448~20.04~260a1a7
  Candidate: 3.36.4-1ubuntu1~20.04.2pop1~1597874448~20.04~260a1a7
  Version table:
 *** 3.36.4-1ubuntu1~20.04.2pop1~1597874448~20.04~260a1a7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     3.36.4-1ubuntu1~20.04.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     3.36.1-5ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
[~] apt policy pop-shell                                                                                
pop-shell:
  Installed: 0.1.0~1601563075~20.04~b553cfc
  Candidate: 0.1.0~1601563075~20.04~b553cfc
  Version table:
 *** 0.1.0~1601563075~20.04~b553cfc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
PopOs 20.04

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Single 1080p horizontal

**(9) Other Installed/Enabled Extensions:**
image

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by mmstick**
Closes #588

### CODE REVIEW

**Comment by jacobgkau** [comment]
Confirmed this fixes the issue with smart gaps not being respected when opening new windows into a stack. I do get this incorrect behavior when moving a window out of the smart-gapped stack:

shell-pr616-screenshot1

Smart gaps should never apply when more than one window is in a workspace/display. I am able to reproduce this on current stable if I close one of the windows in the stack and then move one of the remaining windows out of the stack, so this is not a regression, but it seems related. @mmstick Is that something that would be easier to address now, or should I open a separate issue for it?

**Comment by mmstick** [comment]
I can fix it here

**Comment by mmstick** [comment]
Okay, I got it to toggle when moving a window in and out of the stack

**Review by jacobgkau — APPROVED** [review]
Looks good to merge to dev.

**Pull request merged**
