### PR TITLE
Fix launch of applications whose entries are in sub-directories

### LINKED ISSUE #1163: Launcher fails to start apps whose desktop files reside in subfolders
**(1) Issue/Bug Description:**

Launcher fails to open apps whose `.desktop` files reside in subfolders of `$XDG_DATA_DIRS/applications`. These apps do appear in the search, but absolutely nothing happens when selecting them---there is no visual feedback and no message logged to `journalctl`.

Common examples are wine apps---these tend to be installed in a directory tree that mirrors the Windows start menu layout, i.e., `$XDG_DATA_DIRS/applications/wine/Programs/Appname/Appname.desktop`.

The applications view and the dock are both able to start such apps.

**(2) Steps to reproduce (if you know):**

* Take any `.desktop` file in `~/local/share/applications` or `/usr/share/applications` and move into a subfolder
* Try starting the app using the applications view to confirm that the desktop entry still works
* Close the app and try starting it using launcher---nothing happens

**(3) Expected behavior:**

App launches. (Subfolders are supported by the Freedesktop desktop entry spec as per <https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#desktop-file-id>.)

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

```
gnome-shell:
  Installed: 3.38.4-1ubuntu3~21.04.1ubuntu1pop1~1623339707~21.04~2a1865d
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1630345490~21.04~0484ffb
```

**(7) Where was Pop Shell installed from:**

```
http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main
```

### PR DESCRIPTION
**Pull request by mmstick**
Adds a debug and error logs to indicate what app is being launched, and if the app failed to be found.

Closes #1163

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm now getting the following messages when replicating #1159:
```
Sep 03 08:36:09 pop-os gnome-shell[2346]: pop-shell: [DEBUG] launching desktop entry: org.gnome.Shell.Extensions
Sep 03 08:36:09 pop-os gnome-shell[2346]: pop-shell:  [INFO] stopping pop-launcher services
Sep 03 08:36:09 pop-os gnome-shell[2346]: Could not create transient scope for PID 6851: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 6851 does not exist.
Sep 03 08:36:09 pop-os gnome-shell[2346]: pop-shell: [ERROR] failed to read response from launcher service: Gio.IOErrorEnum: Operation was cancelled
```

Does this give enough info for that issue to be fixed in this PR, or is this PR just to add the additional logging?

**Comment by mmstick** [comment]
The logs indicate that it did find an app and did launch it. The error about transient scopes happens any time GNOME Shell launches a process. I'm really not sure why Shell.App.launch is failing to launch the extensions app. 🤔

**Comment by mmstick** [comment]
Just wondering, but does this appear in both Intel and NVIDIA graphics?

**Comment by jacobgkau** [comment]
> Just wondering, but does this appear in both Intel and NVIDIA graphics?

On oryp7, the issue occurs in NVIDIA mode and Integrated mode, yes. (It also happens on the serw12, which is NVIDIA-only.)

**Comment by mmstick** [comment]
`Shell.App.launch` can return an exception. I've added a try-catch that will log the exception. Maybe it's having an exception?

**Comment by jackpot51** [comment]
I'm on AMD graphics, but I'm also on 21.10 with GNOME 40. @jacobgkau what distro are you on?

**Comment by jacobgkau** [comment]
I'm on Pop!_OS 21.04 with GNOME 3.38.

I'm not getting any additional log lines with 7ff3028, still just the four lines I posted before.

**Comment by mmstick** [comment]
I'm on 21.10 with GNOME 40.2 `22eebbc`. But both Intel and NVIDIA is working for me. Maybe I'll try it out on a clean install in a VM.

**Comment by mmstick** [comment]
I wasn't able to replicate the issue in a VM, but I did push a change that may fix the problem.

**Comment by jacobgkau** [comment]
0ecc4ec on this branch doesn't fix the problem, but the `deduplicate` branch of pop-launcher (at commit c8f03e8) does fix the problem, with or without this `launcher-fail` pop-shell branch. Does that say anything about the underlying cause?

**Comment by mmstick** [comment]
More than one version of the extensions app installed?

**Comment by jacobgkau** [comment]
> More than one version of the extensions app installed?

I'm not sure where the second one would be coming from. The Pop!_Shop shows available sources of `Ubuntu (.deb)` and `flathub (flatpak)`, but only the .deb version is installed by default. (I do know some other distros, such as Fedora, only have the flatpak version available.)

**Comment by mmstick** [comment]
Try the extensions-fix branch of the launcher. Maybe it's conflicting with `org.gnome.Shell.Extensions`

**Review by jacobgkau — APPROVED** [review]
This gets Wine apps (which have their .desktop files in subdirectories) opening up as expected. Launcher regression testing passed on Hirsute and Focal (`launcher.ts` is the only file being modified in this PR.)

**Comment by jacobgkau** [comment]
While this solves the problem, https://github.com/pop-os/shell/issues/1163#issuecomment-914678287 should be taken into account for the engineering review. If I'm understanding correctly, we're not creating the desktop entry ID using the logic specified by FreeDesktop.

**Comment by mmstick** [comment]
@jacobgkau This last commit will get the correct AppID.

**Review by jacobgkau — APPROVED** [review]
The last commit didn't change deduplication behavior (which makes sense, since that code runs when launching a result, not before.) The fix still works/WINE apps with .desktop files in subdirectories still launch correctly on this branch.

**Comment by danielwe** [comment]
Wow, not only was a fix committed to master within a couple of days, it even landed on my box through the regular 21.04 repo almost immediately. Highly appreciated! :100:

**Pull request merged**
