### PR TITLE
fix(tiling): Delay focus check in case window is not focused yet

### LINKED ISSUE #1312: JetBrains IDE (PyCharm, PHPStorm etc) does not receive keyboard input when using tiling and gnome-terminal window is visible.
**(1) Issue/Bug Description:**

I have a strange issue while using JetBrains PyCharm on the primary screen and a gnome terminal on a secondary screen: keyboard input does not go to the PyCharm window, but instead appears inside the terminal.

Tiling is enabled, but it seems to also happen when disabling tiling for those windows.

Maybe related: when I stacked a terminal window and PyCharm, I was not able to interact with the IDE at all, all input - including mouse - seemed to go to the terminal instead. Stacking two PyCharm windows works fine, introducing a terminal makes all keyboard input go to the terminal. Same when having the terminal somewhere else on the primary or secondary screen.

I have the latest versions of Pop!_OS packages as of now (there were a bunch of updates a few hours ago).

**(2) Steps to reproduce (if you know):**

Open PyCharm/a JetBrains IDE. Also open a Gnome-Terminal window on one of the visible monitors.

**(3) Expected behavior:**

Focused window receives keyboard input, so PyCharm works like the editor it is :)

**(4) Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**

Shipped with 21.10: 40.4.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```1.1.0~1641595320~21.10~c3d93f8```

**(7) Where was Pop Shell installed from:**

Pop!_OS installation medium (usb).

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1080p laptop screen to the left, primary 4k monitor landscape, secondary 4k monitor in portrait to the right.

**(9) Other Installed/Enabled Extensions:**

- AppIndicator
- Caffeine
- Desktop Icons NG
- GSConnect
- Jiggle
- OpenWeather
- Sound Input & Output Device Chooser
- system-monitor
- Transparent Top Bar (Adjustable transparency)
- User Themes

And the built-in ones, all enabled.

**(10) Other Notes:**

Thanks for fixing the transparent top bar/panel functionality :)

### PR DESCRIPTION
**Pull request by mmstick**
Fixes #1312

### CODE REVIEW

**Review by leviport — APPROVED** [review]
Could reproduce #1312 on my gaze10 before adding the fix. Confirmed that this fixes it!

Edit: noticed this is going into `master`, so this needs regression testing before approval.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Also confirmed this fixes https://github.com/pop-os/shell/issues/1312 on 21.10 and 20.04.

Regression testing passed:
[shell-pr1314-impish.txt](https://github.com/pop-os/shell/files/7856786/shell-pr1314-impish.txt)
[shell-pr1314-focal.txt](https://github.com/pop-os/shell/files/7856951/shell-pr1314-focal.txt)

**Comment by StarpTech** [comment]
Hi, thank you for the fix. When will it be released?

**Comment by jacobgkau** [comment]
> Hi, thank you for the fix. When will it be released?

It will be released once this package management PR is merged and the build server has a chance to make the release: https://github.com/pop-os/repo-release/pull/17

**Comment by StarpTech** [comment]
@jacobgkau thanks!

**Pull request merged**
