### PR TITLE
Fix pointer jumping & title bar minimizing

### LINKED ISSUE #841: Clicking top bar teleports cursor to top left of maximized window
**(1) Issue/Bug Description:**
When the pop! shell extension is enabled, this strange behaviour occurs:
When a window is maximized and I click somewhere on the top bar of the Gnome shell where there is empty space (eg. next to the time), then my mouse cursor is instantly teleported to the left onto the close button of the maximized window.

**(2) Steps to reproduce (if you know):**
Enable pop! shell extension, maximize some window, click on the gnome top bar

**(3) Expected behavior:**
the mouse stays where the click was made

**(4) Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**
GNOME Shell 3.38.2

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```1.1.0~1610693127~20.10~1557528```

**(7) Where was Pop Shell installed from:**
preinstalled

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
dual monitor 2x 1080p, both horizontal, left primary

**(9) Other Installed/Enabled Extensions:**
nothing too fancy

**(10) Other Notes:**

### LINKED ISSUE #842: Minimize button doesnt work when pop shell enabled
**(1) Issue/Bug Description:**
I enabled minimize button with gnome tweaks. After a recent update, the button stops working. 
When I disable pop shell from extensions, the minimize button works

**(2) Steps to reproduce (if you know):**
1. Enable minimize button
2. Open tilix or chrome app (that's the one which I have knowledge about)
3. Click minimize button and observe the behaviour

**(3) Expected behaviour:**
Minimize button should minimize the window

**(4) Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

### PR DESCRIPTION
**Pull request by mmstick**
Fixes two recent regressions

Closes #841
Closes #842

### CODE REVIEW

**Comment by rengare** [comment]
The commit fixes #842

**Comment by jacobgkau** [comment]
Confirmed this fixes #841. I'm not seeing #842 occur before the change.

This does cause a regression in the mouse cursor movement (when navigating windows with the keyboard.) After the change, the mouse cursor gets stuck in the bottom-right window on a display and doesn't move to the other windows when they are focused: https://www.dropbox.com/s/zlvq5vwoszr0wds/shell-pr843-screencast1.webm?dl=0

**Comment by mmstick** [comment]
@jacobgkau Thought of a different approach, and this works better so that doesn't happen

**Comment by jacobgkau** [comment]
After seeing the most recent comment on #842, I was able to reproduce that issue with VS Code. I can confirm both #841 and #842 are still fixed by this PR.

I am still seeing the cursor get stuck when navigating windows when going from right to left or bottom to top: https://www.dropbox.com/s/om7eplketuc423e/shell-pr843-screencast2.mkv?dl=0 

Although it may have to do with the application and not just the position. Here, the cursor switches from Terminal to VS Code but not from Terminal to the Pop Shop, even after swapping the positions of VS Code and the Pop Shop: https://www.dropbox.com/s/b1dqe7m04w9esxp/shell-pr843-screencast3.mkv?dl=0

**Comment by TJonCooper** [comment]
Still seeing the issue on a subset of apps, including Brave.

**Comment by jmbuhr** [comment]
The jumping also appears when dragging the left of 2 windows onto another workspace via the activities overview.

**Comment by jacobgkau** [comment]
The cursor is no longer getting stuck on certain windows with `2b0950a`. #841 and #842 are still fixed. I see the following remaining problems:

- As mentioned by @jmbuhr, the cursor moves to the top left of the screen after dragging a window in the top left of a tree to a new workspace with the mouse.
- If the cursor is hovering over the top bar, then it doesn't move when focusing windows with the keyboard.

The second one is not happening on master (`1557528`) and is therefore a regression. @mmstick Would that be reasonable to fix?

**Comment by jmbuhr** [comment]
Not sure if this helps, but the second point of @jacobgkau , the non-moving of the cursor if it is over the top bar, does not occur when an external monitor is used as the primary display (so it has the top bar) and a laptop monitor is also in use. In that event the cursor is moved upon focusing. With other monitor configurations the problem does occur.

**Comment by mmstick** [comment]
All should be fixed now

**Comment by jacobgkau** [comment]
Cursor is now jumping when it's supposed to (and only when it's supposed to), I'm still able to minimize VS Code.

https://github.com/pop-os/shell/issues/816 is happening again. https://github.com/pop-os/shell/pull/830 was merged 8 days ago, and this PR was opened 2 days ago. Looking at the code, this PR is undoing the only change from that PR.

@mmstick I'm going to finish regression testing and then approve this (if there are no other regressions) since the missed regressions from #830 seem to be having a larger impact (based on the number of opened issues I've seen this week), but we'll need to re-open #816 if we merge this.

**Review by jacobgkau — APPROVED** [review]
Regression testing passed (aside from the previously-noted #816):
[shell-pr843-groovy-run2.txt](https://github.com/pop-os/shell/files/5858132/shell-pr843-groovy-run2.txt)
[shell-pr843-focal-run2.txt](https://github.com/pop-os/shell/files/5858542/shell-pr843-focal-run2.txt)

**Comment by Bananaman** [comment]
@mmstick Awesome, thanks for finding and fixing those annoying issues!

Does this patch also fix this recent pop-shell tiling bug? https://github.com/pop-os/shell/issues/846

**Comment by mmstick** [comment]
If it's not mentioned in the notes and closed on merged, it's not fixed by the PR.

That said, I can't replicate the issue you linked.

**Comment by antechdesigns** [comment]
I just updated pop os which I assume is the fix for this bug. Unfortunately its still the same after a reboot.

**Upgrade:** 
pop-shell-plugin-system76-power:amd64 (1.1.0~1610693127~20.04~1557528, 1.1.0~1611165402~20.04~5046711)

pop-shell:amd64 (1.1.0~1610693127~20.04~1557528, 1.1.0~1611165402~20.04~5046711)

I just updated pop os which I assume is the fix for this bug. Unfortunately its still the same after a reboot.

**OS: Pop!_OS 20.04 LTS x86_64**
**Kernel: 5.8.0-7630-generic**

Thanks

**Comment by jacobgkau** [comment]
@antechdesigns Once packages are merged into the master branch, they remain in proposed until they're manually released into stable (on Launchpad.) Please wait until you see the version ending with `2b9e4a4` installed, then you will have this update. (You can see [here](https://github.com/pop-os/shell/commits/master) that the version you posted is from earlier this week.)

**Comment by antechdesigns** [comment]
Oh I see, I was a bit confused as I only just got them updates literally 90mins ago and been using pop os for about a week, thought they we're the fixes.

Guess I'll have to wait, you guys are doing a great job, keep up the good work ;)

ant

**Comment by antechdesigns** [comment]
Just got the updates, everything seems fine ;)

thanks a lot all

**Comment by antechdesigns** [comment]
After testing this extensively there seems to be another problem.

**To replicate:** 
with desktop showing only.

- Open a program, in my case I opened settings from the dock
- minimize the program back to the dock
- click applications button on the dock to open

**the bug:**
after clicking the application button again to close it, the last window that was on the desktop now pops back up and the mouse cursor jumps to the top left of the application, (settings in this example) It happens with most programs I have tested, depends on the last window you minimized.

Thanks
ant

**Pull request merged**
