### PR TITLE
fix: Window opening on dual screen #1183

### PR DESCRIPTION
**Pull request by LinuxHeki**
I have no idea what I changed, but now is working perfectly!

### CODE REVIEW

**Comment by LinuxHeki** [comment]
Do I need to delete repo, fork this repo and make changes in one commit?

**Comment by mmstick** [comment]
```
git reset --soft 130ac4f
git commit --amend
```

As long as QA is okay with the window attaching to the display that the mouse is on, regardless of which window is actively focused. Because GNOME always opens the window on the display where the mouse is.

**Comment by LinuxHeki** [comment]
Is this what I need to do?

**Comment by LinuxHeki** [comment]
Sorry

**Comment by isantop** [comment]
I believe you can get what is needed with the following:

```
git fetch
git reset --soft origin/master
git add .
git commit --amend
git push -f
```

**Comment by isantop** [comment]
I see the issue. You need to do as follows:

```
git fetch upstream
git reset --soft upstream/master
git add .
git commit --amend
git push -f -u origin master

**Comment by isantop** [comment]
It looks like those are the changes to our local master branch which you had previously merged in as a merge commit. It shouldn't be a problem, provided the Engineering review still checks out.

**Comment by LinuxHeki** [comment]
Now should work with Minecraft 1.17 but not with Minecraft 1.8

**Comment by LinuxHeki** [comment]
Every single window opened on display where the mouse was. Now is fixed. Do I squash into one commit again?

**Comment by LinuxHeki** [comment]
If you press F11 three times is working...

**Pull request closed without merging**
