### PR TITLE
Fix exception for Firefox

### PR DESCRIPTION
**Pull request by jackpot51**
Fixes https://github.com/pop-os/beta/issues/2

### CODE REVIEW

**Comment by jeroen7s** [comment]
not sure if hardcoding a specific application name is the best solution for this.
Tor browser has the same issue btw, maybe some other applications that i'm not yet aware of.

**Comment by mmstick** [comment]
We can use an array as we're already doing for blacklisting certain windows from tiling that violate X11 window manager standards (applications not hinting the window manager that they are dialogs, utilities, etc.). Firefox doesn't tell us that it's doing its own brand on client-side rendering, so it needs some special case handling. We can add Tor too. What is the window name?

**Comment by jeroen7s** [comment]
Window name for Tor is "Tor Browser"

**Comment by jeroen7s** [comment]
Though I'm not sure if messing with window borders is nessecary for tiling? 
Shouldn't the default be "don't touch window borders", instead of forcing all borders either on or of?
Seems like the window name fix breaks with non-english languages. https://github.com/pop-os/beta/issues/2#issuecomment-622781464

**Pull request merged**
