### PR TITLE
feat: apply hint color on tabs

### PR DESCRIPTION
**Pull request by jmmaranan**
Use the current active hint logic to apply to the stacking button tab

### CODE REVIEW

**Comment by jacobgkau** [comment]
This seems to be working fairly well. One potential concern is the text in the tabs being unreadable with dark colors. As an extreme example, take a solid black active hint:

shell-pr596-screenshot1

The active hint is subtle but still visible (some users might prefer this to a bright, highlighted color), and the tab bar is obviously unreadable. Would it be possible to switch the text color in the tabs from black to white if the lightness/luminance of the hint color is below a certain threshold? Something like what's discussed here: https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color

**Comment by jmmaranan** [comment]
Sure, I think that's doable. Thanks for the formula link. I'll check it out

**Comment by jmmaranan** [comment]
@jacobgkau - this is ready for test - the link to the advanced computation of contrast works well

**Review by mmstick — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Looks great!

**Pull request merged**
