### PR TITLE
Shell Fixes

### LINKED ISSUE #1268: Persistent active window highlight upon minimizing
**(1) Issue/Bug Description:**
 The Active window highlight persists when minimizing a window. Very similar to #1129 but the issue occurs even when not in "adjustment mode" for resizing. I have attached a recording of the issue to explain further.

https://user-images.githubusercontent.com/67309153/144962179-60fc83b0-98b3-4d15-b201-124729d82e77.mp4

**(2) Steps to reproduce (if you know):**
 -> Enable active window highlight
 -> Open any window
 -> Minimize the window

**(3) Expected behavior:**
Active window highlight should disappear, as the window is minimized and not active at the moment. 

**(4) Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
GNOME Shell 3.38.4

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
``` 
pop-shell:
  Installed: 1.1.0~1638556835~21.04~b2cfd69
  Candidate: 1.1.0~1638556835~21.04~b2cfd69
  Version table:
 *** 1.1.0~1638556835~21.04~b2cfd69 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**
Installed by default with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
Dash to panel, Blur my shell, User Themes

**(10) Other Notes:**
Does not occur when there is another window open (not minimized) in the same workspace, it works as expected and switches the highlight from the minimized window to the next active window.

### LINKED ISSUE #1298: Closing a window that is being focused in adjustment mode causes the active hint to stay where it was rather than moving onto the new focused window
**(1) Issue/Bug Description:**

If you close a window that is focused in adjustment mode, the active hint overlay will remain at the location of the window that you closed rather than moving onto the new focused window. 

**(2) Steps to reproduce (if you know):**

1. Open two windows side by side
2. Hit super + return to enter adjustment mode, noting the currently focused window
3. Hit super + q to close the currently focused window

**(3) Expected behavior:**

The active hint moves onto the other window instead of remaining at the location of the window that has been closed

**(4) Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**(5) Gnome Shell version:**

40.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1639174177~21.10~de901ae
  Candidate: 1.1.0~1639174177~21.10~de901ae
  Version table:
 *** 1.1.0~1639174177~21.10~de901ae 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:**

Came with Pop!_OS

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

1 x 1080p

**(9) Other Installed/Enabled Extensions:**

None

**(10) Other Notes:**

### LINKED ISSUE #1303: Launching new window sometimes changes focus to existing window
**(1) Issue/Bug Description:** When launching a new window of certain apps (including GNOME Terminal and KWrite), if I already had that app open on another workspace, I sometimes get my focus switched to the existing window/workspace. (The new window does open up on the workspace I requested it from, but it's not focused.)

**(2) Steps to reproduce (if you know):**
1. Open GNOME Terminal
2. Switch to another workspace
3. Using the Launcher, open another instance of GNOME Terminal
4. If necessary close that one and repeat step 3 a second time

**(3) Expected behavior:** I should not be switched away from the workspace where the new window is opening.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 21.10

**(5) Gnome Shell version:** 40

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):** de901ae, d7dfb35 

**(7) Where was Pop Shell installed from:** Release and staging repos.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1x 1080p

**(9) Other Installed/Enabled Extensions:** N/A

**(10) Other Notes:**

https://user-images.githubusercontent.com/7199422/148114810-b167879c-972b-4496-a69b-3b42239a8083.mp4

### PR DESCRIPTION
**Pull request by mmstick**
- Fixes pointer placement when window is raised when clicking stack tab
- Fixes loss of focus when clicking a stack tab or background gap
- Fixes tiling overlay remaining shown after destroying window
- Fixes focus moving outside of stack when closing window in stack
- Fixes border remaining shown in floating mode when minimizing window
- Removes some deprecated code

Closes #1268
Closes #1298
Closes #1303

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
https://github.com/pop-os/shell/pull/1261 was already fixed and this PR doesn't seem to make any changes to the readme, were there any other issues besides #1298 and #1268 that you intended to close with this?

**Review by jacobgkau — CHANGES_REQUESTED** [review]
When launching an app from the dock or the App Library, the app's window is no longer being focused:

https://user-images.githubusercontent.com/7199422/147980576-8c427449-5a2b-43be-8cb2-f5d61fbbbc82.mp4

This doesn't affect apps launched from the Launcher.

**Comment by mmstick** [comment]
Wrong issue linked. I'm sure there's a handful of issues these resolve.

**Comment by jacobgkau** [comment]
Nearly finished regression testing, but found another issue. If I have a stack with three or more windows, and I float one of them with Super+G, the stack now retains focus, instead of the newly-floated window.

**Comment by jacobgkau** [comment]
On 02b3fd3, I'm getting my mouse cursor moved to the top left of the display every time I open an app/window.

**Comment by jacobgkau** [comment]
On d363b9f, I am now getting the mouse cursor moved to the top-left of the window every time I open an app from the dock.

When using the App Library, this behavior might make sense. However, I'm not sure it makes sense for the dock. I can no longer quickly go down a list of icons to open up a set of apps; I have to keep moving my cursor back to the dock after every launch.

Even for the App Library, it feels a little jarring. As a fairly mouse-centric user, any time the mouse moves while I'm actively using it, it feels disorienting. The cursor should probably only move by itself in response to keyboard operations.

Unrelated, but I also had a Calculator window not resize to fill its space after launching via App Library with the mouse:

Screenshot from 2022-01-05 11-21-22

When I went to resize it manually, it started tiling normally; it didn't happen again when I closed and re-launched a few times.

**Comment by mmstick** [comment]
In that case, the best option would be to only move the pointer when a Pop Shell keyboard shortcut is used to move focus between windows, and not when windows are created or focused.

**Comment by jacobgkau** [comment]
Haven't finished full regression testing yet, but cursor movement looks more in line with what's currently released now.

Do you think it would be a good idea to have the cursor follow a window after it's moved/swapped with the keyboard? The currently-released version doesn't do that, but it seems like it might be more consistent.

**Comment by mmstick** [comment]
Yes it would make sense to do that.

**Comment by jacobgkau** [comment]
Very subtle change in behavior: with tiling disabled, if I maximize a window (e.g. Terminal), then launch another window (e.g. Calculator) using the Launcher, the new Calculator window is opened in the foreground (above the maximized Terminal window), but it is not focused; Terminal remains focused.

If I launch Calculator from the App Library, then it's focused as expected.

**Comment by jacobgkau** [comment]
Also, I wasn't going to bring this up if everything else looked okay, but since more revisions are needed anyway: it occurred to me that the cursor could also move to the focused window when switching orientation with the keyboard (Super + O) and potentially also when floating a window with the keyboard (Super + G). The cursor not moving on those operations stuck out a little bit now that the rest of the shortcuts are consistently moving the cursor.

**Comment by jacobgkau** [comment]
If I drag a window out of a stack with the mouse into the _same_ tree, the dragged window is focused, as expected. If I drag it into a _different_ tree, the remaining window from the stack is focused instead, which is inconsistent.

https://user-images.githubusercontent.com/7199422/148442736-66c8ea70-c48d-4a25-b26e-cb46cf3bfce3.mp4

**Comment by mmstick** [comment]
So close. Will get it fixed

**Comment by jacobgkau** [comment]
When I have Settings open, switch to another workspace, and search in the Launcher for a Settings panel other than the one that was open, the correct panel does get switched to, but I do not get moved to the workspace that Settings is on. This is a regression.

**Comment by jacobgkau** [comment]
It doesn't look like a88d5ac has fixed that issue, I still don't get switched to the correct workspace when searching for a Settings panel from another workspace.

**Comment by mmstick** [comment]
I'll make it switch after idling if that's the cause. It is working fine on my end.

**Comment by mmstick** [comment]
I found a better solution for handling gnome-control-center panels. This should be more reliable with getting workspace switching working.

**Comment by jacobgkau** [comment]
If I launch an app that wasn't already open using the Launcher and keyboard, I used to get the mouse cursor moved to the top-left of that new app/window, but I no longer do. Before:

https://user-images.githubusercontent.com/7199422/148609618-535712b5-9e3b-46ea-b5f2-0d2b86f43794.mp4

After:

https://user-images.githubusercontent.com/7199422/148609620-d6819943-9dd5-4d41-a77b-a6e83234b0c6.mp4

I see where we made this change earlier, somewhat intentionally. Would it be possible for the cursor to move if the user presses Enter in the launcher, but not if they click the result? If that's not possible right now, then I think we could let this one go, but I wanted to check.

(I first noticed that selecting Settings page search results while Settings is already open does not move the mouse cursor, but that one's not a regression.)

**Comment by mmstick** [comment]
It's not possible at the moment, but might be possible to achieve with some work.

**Review by jacobgkau — APPROVED** [review]
Mouse cursor aside, workspace switching for Settings pages is working now, and seems faster than before.

Confirmed this fixes #1268 (minimizing a floating single window no longer leaves its active hint on the desktop), #1298 (closing a window with Super-Q now exits adjustment mode), and #1303 (launching new KWrite/Terminal windows no longer switches me to the wrong workspace).

Regression testing passed:
[shell-pr1299-impish.txt](https://github.com/pop-os/shell/files/7831397/shell-pr1299-impish.txt)
[shell-pr1299-focal.txt](https://github.com/pop-os/shell/files/7831648/shell-pr1299-focal.txt)

**Pull request merged**
