### PR TITLE
fix: Close launcher dialog on screen lock

### LINKED ISSUE #688: Super + / launcher stays activated in the lock screen
### (1) Issue/Bug Description:
The `Super`+`/` launcher stays activated in the lock screen. You can even select opened windows and search works too.

### (2) Steps to reproduce (if you know):
Activate The `Super`+`/` launcher then lock the screen.

### (3) Expected behaviour:
The launcher should not be shown and accessed from the the lock screen.

### (4) Distribution (run `cat /etc/os-release`):
**NAME=Fedora
VERSION="33 (Workstation Edition)"**
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

### (5) Gnome Shell version:
GNOME Version: `3.38.1`
Windowing System `Wayland`

### (6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):

Commit :`18243a26b2177c3d13a8af4c05050d5deb29790c`

### (7) Where was Pop Shell installed from:
https://github.com/pop-os/shell

### (8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):
1 x 1080p

### (9) Other Installed/Enabled Extensions:
- User Themes
- Native Window Placement
- Background Logo (Fedora)

### (10) Screenshot(s):
IMG_20201106_134231

### PR DESCRIPTION
**Pull request by mmstick**
Closes #688

### CODE REVIEW

**Comment by jacobgkau** [comment]
Confirmed this fixes https://github.com/pop-os/shell/issues/688 on a Wayland session in Fedora. (The issue did not seem to affect Xorg.)

No regressions on Pop!_OS. I did notice that when the launcher is closed due to locking the screen, the next time it's opened, it still displays the previously-typed text, but that text doesn't affect the search results until another character is typed. (Until another character is added/removed, the list of open windows is displayed, regardless of the saved text in the launcher.) Steps to reproduce:

- Open the launcher while windows are open
- Type some text that doesn't match any open windows
- Lock the screen
- Unlock the screen
- Open the launcher

Either the text should be cleared out when the screen is locked (like how it's cleared when the launcher is closed using the `Esc` key), or the saved text should affect the search results upon re-opening the launcher. @mmstick Should I open an issue for that, or would it be simple enough to deal with in this PR? (It was happening in Pop/Xorg even before this PR, but was not happening on Wayland since the launcher wasn't being closed.)

**Comment by mmstick** [comment]
I can have it cleared here

**Comment by jacobgkau** [comment]
After that last change, the text is cleared from the launcher when locking, but the active window's highlight is visible on the lock screen (even when the launcher isn't open when I lock the screen): https://www.dropbox.com/s/jnms1ao0z207u33/2020-11-06%2016-44-26.mkv?dl=0

On Fedora (both Wayland and X11), the window's highlight stays there until the launcher is opened and interacted with again: https://www.dropbox.com/s/nt6t8gck6r3j28s/2020-11-06%2016-45-04.mkv?dl=0

**Review by jacobgkau — APPROVED** [review]
Now working as expected on both X11 and Wayland.

While regression testing, I noticed that https://github.com/pop-os/shell/pull/692 hasn't been applied in this branch yet, but I don't see a button to merge master into this branch... not sure what's going on there, but I assume this PR won't undo the previous PR since the change to `window.ts` isn't listed under files changed.

**Pull request merged**
