### PR TITLE
feat: Improvements to UX for stack tabs

### PR DESCRIPTION
**Pull request by mmstick**
Screenshot from 2022-08-05 16-55-50

### CODE REVIEW

**Review by n3m0-22 — APPROVED** [review]
All new features look good, and are working correctly. All shell testing passed.

[shell-testing-tabs.txt](https://github.com/pop-os/shell/files/9283705/shell-testing-tabs.txt)

**Review by 13r0ck — APPROVED** [review]

**Comment by gma** [comment]
I appreciate this is very subjective, but I really enjoyed the cleanliness of the tabs without the icons (sorry).

Are there any plans to make their visibility configurable? I've had a look at the patch and can't see any code in there to support it right now, but I'm not familiar with this repo so could have missed it.

Cheers!

**Comment by mmstick** [comment]
I could make it configurable

**Comment by gma** [comment]
I'd really love to be able to toggle it off with something like a dconf key, if it's not too much trouble or extra complexity. But I realise that the more settings we have, the higher the maintenance cost.

**Comment by mmstick** [comment]
Maintenance cost for a dconf toggle is virtually zero

**Pull request merged**
