### PR TITLE
fix: check if extension local schemas dir exists before use

### PR DESCRIPTION
**Pull request by lleyton**
Should resolve the issue the Fedora peeps are having in https://github.com/pop-os/shell/issues/1649 :3

### CODE REVIEW

**Comment by carlwgeorge** [comment]
I included this change as a patch to the Fedora package, and it worked great.  Thanks!

**Comment by s373r** [comment]
Just tested -- works great!

Many thanks to you!

**Review by mmstick — APPROVED** [review]

**Comment by nitin88** [comment]
@jacobgkau Can you please review the same?

**Review by jacobgkau — APPROVED** [review]
The extension seems to work fine with this change on both Ubuntu 23.10 and Fedora 39. This does get rid of the error message in the logs when the `pop-shell@system76.com/schemas` dir isn't present on Fedora.

This change doesn't affect Pop!_OS since it's going into `master_mantic`.

**Pull request merged**
